/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ChannelSettings;
import org.openapitools.client.model.ImageSettings;
import org.openapitools.client.model.PropertyValue;
import org.openapitools.client.model.WatchSettings;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ChannelBrandingSettings
 */
public class ChannelBrandingSettingsTest {
    private final ChannelBrandingSettings model = new ChannelBrandingSettings();

    /**
     * Model tests for ChannelBrandingSettings
     */
    @Test
    public void testChannelBrandingSettings() {
        // TODO: test ChannelBrandingSettings
    }

    /**
     * Test the property 'channel'
     */
    @Test
    public void channelTest() {
        // TODO: test channel
    }

    /**
     * Test the property 'hints'
     */
    @Test
    public void hintsTest() {
        // TODO: test hints
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'watch'
     */
    @Test
    public void watchTest() {
        // TODO: test watch
    }

}
