/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ChannelLocalization;
import org.openapitools.client.model.ThumbnailDetails;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ChannelSnippet
 */
public class ChannelSnippetTest {
    private final ChannelSnippet model = new ChannelSnippet();

    /**
     * Model tests for ChannelSnippet
     */
    @Test
    public void testChannelSnippet() {
        // TODO: test ChannelSnippet
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'customUrl'
     */
    @Test
    public void customUrlTest() {
        // TODO: test customUrl
    }

    /**
     * Test the property 'defaultLanguage'
     */
    @Test
    public void defaultLanguageTest() {
        // TODO: test defaultLanguage
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'localized'
     */
    @Test
    public void localizedTest() {
        // TODO: test localized
    }

    /**
     * Test the property 'publishedAt'
     */
    @Test
    public void publishedAtTest() {
        // TODO: test publishedAt
    }

    /**
     * Test the property 'thumbnails'
     */
    @Test
    public void thumbnailsTest() {
        // TODO: test thumbnails
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

}
