/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.ChannelSectionContentDetails;
import org.openapitools.client.model.ChannelSectionLocalization;
import org.openapitools.client.model.ChannelSectionSnippet;
import org.openapitools.client.model.ChannelSectionTargeting;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ChannelSection
 */
public class ChannelSectionTest {
    private final ChannelSection model = new ChannelSection();

    /**
     * Model tests for ChannelSection
     */
    @Test
    public void testChannelSection() {
        // TODO: test ChannelSection
    }

    /**
     * Test the property 'contentDetails'
     */
    @Test
    public void contentDetailsTest() {
        // TODO: test contentDetails
    }

    /**
     * Test the property 'etag'
     */
    @Test
    public void etagTest() {
        // TODO: test etag
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'kind'
     */
    @Test
    public void kindTest() {
        // TODO: test kind
    }

    /**
     * Test the property 'localizations'
     */
    @Test
    public void localizationsTest() {
        // TODO: test localizations
    }

    /**
     * Test the property 'snippet'
     */
    @Test
    public void snippetTest() {
        // TODO: test snippet
    }

    /**
     * Test the property 'targeting'
     */
    @Test
    public void targetingTest() {
        // TODO: test targeting
    }

}
