/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CommentThread;
import org.openapitools.client.model.PageInfo;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CommentThreadListResponse
 */
public class CommentThreadListResponseTest {
    private final CommentThreadListResponse model = new CommentThreadListResponse();

    /**
     * Model tests for CommentThreadListResponse
     */
    @Test
    public void testCommentThreadListResponse() {
        // TODO: test CommentThreadListResponse
    }

    /**
     * Test the property 'etag'
     */
    @Test
    public void etagTest() {
        // TODO: test etag
    }

    /**
     * Test the property 'eventId'
     */
    @Test
    public void eventIdTest() {
        // TODO: test eventId
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'kind'
     */
    @Test
    public void kindTest() {
        // TODO: test kind
    }

    /**
     * Test the property 'nextPageToken'
     */
    @Test
    public void nextPageTokenTest() {
        // TODO: test nextPageToken
    }

    /**
     * Test the property 'pageInfo'
     */
    @Test
    public void pageInfoTest() {
        // TODO: test pageInfo
    }

    /**
     * Test the property 'tokenPagination'
     */
    @Test
    public void tokenPaginationTest() {
        // TODO: test tokenPagination
    }

    /**
     * Test the property 'visitorId'
     */
    @Test
    public void visitorIdTest() {
        // TODO: test visitorId
    }

}
