/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LiveChatMessageRetractedDetails
 */
public class LiveChatMessageRetractedDetailsTest {
    private final LiveChatMessageRetractedDetails model = new LiveChatMessageRetractedDetails();

    /**
     * Model tests for LiveChatMessageRetractedDetails
     */
    @Test
    public void testLiveChatMessageRetractedDetails() {
        // TODO: test LiveChatMessageRetractedDetails
    }

    /**
     * Test the property 'retractedMessageId'
     */
    @Test
    public void retractedMessageIdTest() {
        // TODO: test retractedMessageId
    }

}
