/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.LiveChatFanFundingEventDetails;
import org.openapitools.client.model.LiveChatMessageDeletedDetails;
import org.openapitools.client.model.LiveChatMessageRetractedDetails;
import org.openapitools.client.model.LiveChatSuperChatDetails;
import org.openapitools.client.model.LiveChatSuperStickerDetails;
import org.openapitools.client.model.LiveChatTextMessageDetails;
import org.openapitools.client.model.LiveChatUserBannedMessageDetails;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LiveChatMessageSnippet
 */
public class LiveChatMessageSnippetTest {
    private final LiveChatMessageSnippet model = new LiveChatMessageSnippet();

    /**
     * Model tests for LiveChatMessageSnippet
     */
    @Test
    public void testLiveChatMessageSnippet() {
        // TODO: test LiveChatMessageSnippet
    }

    /**
     * Test the property 'authorChannelId'
     */
    @Test
    public void authorChannelIdTest() {
        // TODO: test authorChannelId
    }

    /**
     * Test the property 'displayMessage'
     */
    @Test
    public void displayMessageTest() {
        // TODO: test displayMessage
    }

    /**
     * Test the property 'fanFundingEventDetails'
     */
    @Test
    public void fanFundingEventDetailsTest() {
        // TODO: test fanFundingEventDetails
    }

    /**
     * Test the property 'hasDisplayContent'
     */
    @Test
    public void hasDisplayContentTest() {
        // TODO: test hasDisplayContent
    }

    /**
     * Test the property 'liveChatId'
     */
    @Test
    public void liveChatIdTest() {
        // TODO: test liveChatId
    }

    /**
     * Test the property 'messageDeletedDetails'
     */
    @Test
    public void messageDeletedDetailsTest() {
        // TODO: test messageDeletedDetails
    }

    /**
     * Test the property 'messageRetractedDetails'
     */
    @Test
    public void messageRetractedDetailsTest() {
        // TODO: test messageRetractedDetails
    }

    /**
     * Test the property 'publishedAt'
     */
    @Test
    public void publishedAtTest() {
        // TODO: test publishedAt
    }

    /**
     * Test the property 'superChatDetails'
     */
    @Test
    public void superChatDetailsTest() {
        // TODO: test superChatDetails
    }

    /**
     * Test the property 'superStickerDetails'
     */
    @Test
    public void superStickerDetailsTest() {
        // TODO: test superStickerDetails
    }

    /**
     * Test the property 'textMessageDetails'
     */
    @Test
    public void textMessageDetailsTest() {
        // TODO: test textMessageDetails
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'userBannedDetails'
     */
    @Test
    public void userBannedDetailsTest() {
        // TODO: test userBannedDetails
    }

}
