/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LiveChatFanFundingEventDetails
 */
public class LiveChatFanFundingEventDetailsTest {
    private final LiveChatFanFundingEventDetails model = new LiveChatFanFundingEventDetails();

    /**
     * Model tests for LiveChatFanFundingEventDetails
     */
    @Test
    public void testLiveChatFanFundingEventDetails() {
        // TODO: test LiveChatFanFundingEventDetails
    }

    /**
     * Test the property 'amountDisplayString'
     */
    @Test
    public void amountDisplayStringTest() {
        // TODO: test amountDisplayString
    }

    /**
     * Test the property 'amountMicros'
     */
    @Test
    public void amountMicrosTest() {
        // TODO: test amountMicros
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'userComment'
     */
    @Test
    public void userCommentTest() {
        // TODO: test userComment
    }

}
