/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ChannelProfileDetails;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LiveChatBanSnippet
 */
public class LiveChatBanSnippetTest {
    private final LiveChatBanSnippet model = new LiveChatBanSnippet();

    /**
     * Model tests for LiveChatBanSnippet
     */
    @Test
    public void testLiveChatBanSnippet() {
        // TODO: test LiveChatBanSnippet
    }

    /**
     * Test the property 'banDurationSeconds'
     */
    @Test
    public void banDurationSecondsTest() {
        // TODO: test banDurationSeconds
    }

    /**
     * Test the property 'bannedUserDetails'
     */
    @Test
    public void bannedUserDetailsTest() {
        // TODO: test bannedUserDetails
    }

    /**
     * Test the property 'liveChatId'
     */
    @Test
    public void liveChatIdTest() {
        // TODO: test liveChatId
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
