/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.SuperStickerMetadata;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LiveChatSuperStickerDetails
 */
public class LiveChatSuperStickerDetailsTest {
    private final LiveChatSuperStickerDetails model = new LiveChatSuperStickerDetails();

    /**
     * Model tests for LiveChatSuperStickerDetails
     */
    @Test
    public void testLiveChatSuperStickerDetails() {
        // TODO: test LiveChatSuperStickerDetails
    }

    /**
     * Test the property 'amountDisplayString'
     */
    @Test
    public void amountDisplayStringTest() {
        // TODO: test amountDisplayString
    }

    /**
     * Test the property 'amountMicros'
     */
    @Test
    public void amountMicrosTest() {
        // TODO: test amountMicros
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'superStickerMetadata'
     */
    @Test
    public void superStickerMetadataTest() {
        // TODO: test superStickerMetadata
    }

    /**
     * Test the property 'tier'
     */
    @Test
    public void tierTest() {
        // TODO: test tier
    }

}
