/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PlaylistItemContentDetails
 */
public class PlaylistItemContentDetailsTest {
    private final PlaylistItemContentDetails model = new PlaylistItemContentDetails();

    /**
     * Model tests for PlaylistItemContentDetails
     */
    @Test
    public void testPlaylistItemContentDetails() {
        // TODO: test PlaylistItemContentDetails
    }

    /**
     * Test the property 'endAt'
     */
    @Test
    public void endAtTest() {
        // TODO: test endAt
    }

    /**
     * Test the property 'note'
     */
    @Test
    public void noteTest() {
        // TODO: test note
    }

    /**
     * Test the property 'startAt'
     */
    @Test
    public void startAtTest() {
        // TODO: test startAt
    }

    /**
     * Test the property 'videoId'
     */
    @Test
    public void videoIdTest() {
        // TODO: test videoId
    }

    /**
     * Test the property 'videoPublishedAt'
     */
    @Test
    public void videoPublishedAtTest() {
        // TODO: test videoPublishedAt
    }

}
