/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubscriptionContentDetails
 */
public class SubscriptionContentDetailsTest {
    private final SubscriptionContentDetails model = new SubscriptionContentDetails();

    /**
     * Model tests for SubscriptionContentDetails
     */
    @Test
    public void testSubscriptionContentDetails() {
        // TODO: test SubscriptionContentDetails
    }

    /**
     * Test the property 'activityType'
     */
    @Test
    public void activityTypeTest() {
        // TODO: test activityType
    }

    /**
     * Test the property 'newItemCount'
     */
    @Test
    public void newItemCountTest() {
        // TODO: test newItemCount
    }

    /**
     * Test the property 'totalItemCount'
     */
    @Test
    public void totalItemCountTest() {
        // TODO: test totalItemCount
    }

}
