/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VideoStatistics
 */
public class VideoStatisticsTest {
    private final VideoStatistics model = new VideoStatistics();

    /**
     * Model tests for VideoStatistics
     */
    @Test
    public void testVideoStatistics() {
        // TODO: test VideoStatistics
    }

    /**
     * Test the property 'commentCount'
     */
    @Test
    public void commentCountTest() {
        // TODO: test commentCount
    }

    /**
     * Test the property 'dislikeCount'
     */
    @Test
    public void dislikeCountTest() {
        // TODO: test dislikeCount
    }

    /**
     * Test the property 'favoriteCount'
     */
    @Test
    public void favoriteCountTest() {
        // TODO: test favoriteCount
    }

    /**
     * Test the property 'likeCount'
     */
    @Test
    public void likeCountTest() {
        // TODO: test likeCount
    }

    /**
     * Test the property 'viewCount'
     */
    @Test
    public void viewCountTest() {
        // TODO: test viewCount
    }

}
