/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.GeoPoint;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VideoRecordingDetails
 */
public class VideoRecordingDetailsTest {
    private final VideoRecordingDetails model = new VideoRecordingDetails();

    /**
     * Model tests for VideoRecordingDetails
     */
    @Test
    public void testVideoRecordingDetails() {
        // TODO: test VideoRecordingDetails
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'locationDescription'
     */
    @Test
    public void locationDescriptionTest() {
        // TODO: test locationDescription
    }

    /**
     * Test the property 'recordingDate'
     */
    @Test
    public void recordingDateTest() {
        // TODO: test recordingDate
    }

}
