/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VideoCategorySnippet
 */
public class VideoCategorySnippetTest {
    private final VideoCategorySnippet model = new VideoCategorySnippet();

    /**
     * Model tests for VideoCategorySnippet
     */
    @Test
    public void testVideoCategorySnippet() {
        // TODO: test VideoCategorySnippet
    }

    /**
     * Test the property 'assignable'
     */
    @Test
    public void assignableTest() {
        // TODO: test assignable
    }

    /**
     * Test the property 'channelId'
     */
    @Test
    public void channelIdTest() {
        // TODO: test channelId
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

}
