/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VideoLiveStreamingDetails
 */
public class VideoLiveStreamingDetailsTest {
    private final VideoLiveStreamingDetails model = new VideoLiveStreamingDetails();

    /**
     * Model tests for VideoLiveStreamingDetails
     */
    @Test
    public void testVideoLiveStreamingDetails() {
        // TODO: test VideoLiveStreamingDetails
    }

    /**
     * Test the property 'activeLiveChatId'
     */
    @Test
    public void activeLiveChatIdTest() {
        // TODO: test activeLiveChatId
    }

    /**
     * Test the property 'actualEndTime'
     */
    @Test
    public void actualEndTimeTest() {
        // TODO: test actualEndTime
    }

    /**
     * Test the property 'actualStartTime'
     */
    @Test
    public void actualStartTimeTest() {
        // TODO: test actualStartTime
    }

    /**
     * Test the property 'concurrentViewers'
     */
    @Test
    public void concurrentViewersTest() {
        // TODO: test concurrentViewers
    }

    /**
     * Test the property 'scheduledEndTime'
     */
    @Test
    public void scheduledEndTimeTest() {
        // TODO: test scheduledEndTime
    }

    /**
     * Test the property 'scheduledStartTime'
     */
    @Test
    public void scheduledStartTimeTest() {
        // TODO: test scheduledStartTime
    }

}
