/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VideoFileDetailsVideoStream
 */
public class VideoFileDetailsVideoStreamTest {
    private final VideoFileDetailsVideoStream model = new VideoFileDetailsVideoStream();

    /**
     * Model tests for VideoFileDetailsVideoStream
     */
    @Test
    public void testVideoFileDetailsVideoStream() {
        // TODO: test VideoFileDetailsVideoStream
    }

    /**
     * Test the property 'aspectRatio'
     */
    @Test
    public void aspectRatioTest() {
        // TODO: test aspectRatio
    }

    /**
     * Test the property 'bitrateBps'
     */
    @Test
    public void bitrateBpsTest() {
        // TODO: test bitrateBps
    }

    /**
     * Test the property 'codec'
     */
    @Test
    public void codecTest() {
        // TODO: test codec
    }

    /**
     * Test the property 'frameRateFps'
     */
    @Test
    public void frameRateFpsTest() {
        // TODO: test frameRateFps
    }

    /**
     * Test the property 'heightPixels'
     */
    @Test
    public void heightPixelsTest() {
        // TODO: test heightPixels
    }

    /**
     * Test the property 'rotation'
     */
    @Test
    public void rotationTest() {
        // TODO: test rotation
    }

    /**
     * Test the property 'vendor'
     */
    @Test
    public void vendorTest() {
        // TODO: test vendor
    }

    /**
     * Test the property 'widthPixels'
     */
    @Test
    public void widthPixelsTest() {
        // TODO: test widthPixels
    }

}
