/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.VideoAgeGating;
import org.openapitools.client.model.VideoContentDetails;
import org.openapitools.client.model.VideoFileDetails;
import org.openapitools.client.model.VideoLiveStreamingDetails;
import org.openapitools.client.model.VideoLocalization;
import org.openapitools.client.model.VideoMonetizationDetails;
import org.openapitools.client.model.VideoPlayer;
import org.openapitools.client.model.VideoProcessingDetails;
import org.openapitools.client.model.VideoRecordingDetails;
import org.openapitools.client.model.VideoSnippet;
import org.openapitools.client.model.VideoStatistics;
import org.openapitools.client.model.VideoStatus;
import org.openapitools.client.model.VideoSuggestions;
import org.openapitools.client.model.VideoTopicDetails;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Video
 */
public class VideoTest {
    private final Video model = new Video();

    /**
     * Model tests for Video
     */
    @Test
    public void testVideo() {
        // TODO: test Video
    }

    /**
     * Test the property 'ageGating'
     */
    @Test
    public void ageGatingTest() {
        // TODO: test ageGating
    }

    /**
     * Test the property 'contentDetails'
     */
    @Test
    public void contentDetailsTest() {
        // TODO: test contentDetails
    }

    /**
     * Test the property 'etag'
     */
    @Test
    public void etagTest() {
        // TODO: test etag
    }

    /**
     * Test the property 'fileDetails'
     */
    @Test
    public void fileDetailsTest() {
        // TODO: test fileDetails
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'kind'
     */
    @Test
    public void kindTest() {
        // TODO: test kind
    }

    /**
     * Test the property 'liveStreamingDetails'
     */
    @Test
    public void liveStreamingDetailsTest() {
        // TODO: test liveStreamingDetails
    }

    /**
     * Test the property 'localizations'
     */
    @Test
    public void localizationsTest() {
        // TODO: test localizations
    }

    /**
     * Test the property 'monetizationDetails'
     */
    @Test
    public void monetizationDetailsTest() {
        // TODO: test monetizationDetails
    }

    /**
     * Test the property 'player'
     */
    @Test
    public void playerTest() {
        // TODO: test player
    }

    /**
     * Test the property 'processingDetails'
     */
    @Test
    public void processingDetailsTest() {
        // TODO: test processingDetails
    }

    /**
     * Test the property 'projectDetails'
     */
    @Test
    public void projectDetailsTest() {
        // TODO: test projectDetails
    }

    /**
     * Test the property 'recordingDetails'
     */
    @Test
    public void recordingDetailsTest() {
        // TODO: test recordingDetails
    }

    /**
     * Test the property 'snippet'
     */
    @Test
    public void snippetTest() {
        // TODO: test snippet
    }

    /**
     * Test the property 'statistics'
     */
    @Test
    public void statisticsTest() {
        // TODO: test statistics
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'suggestions'
     */
    @Test
    public void suggestionsTest() {
        // TODO: test suggestions
    }

    /**
     * Test the property 'topicDetails'
     */
    @Test
    public void topicDetailsTest() {
        // TODO: test topicDetails
    }

}
