/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.VideoProcessingDetailsProcessingProgress;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VideoProcessingDetails
 */
public class VideoProcessingDetailsTest {
    private final VideoProcessingDetails model = new VideoProcessingDetails();

    /**
     * Model tests for VideoProcessingDetails
     */
    @Test
    public void testVideoProcessingDetails() {
        // TODO: test VideoProcessingDetails
    }

    /**
     * Test the property 'editorSuggestionsAvailability'
     */
    @Test
    public void editorSuggestionsAvailabilityTest() {
        // TODO: test editorSuggestionsAvailability
    }

    /**
     * Test the property 'fileDetailsAvailability'
     */
    @Test
    public void fileDetailsAvailabilityTest() {
        // TODO: test fileDetailsAvailability
    }

    /**
     * Test the property 'processingFailureReason'
     */
    @Test
    public void processingFailureReasonTest() {
        // TODO: test processingFailureReason
    }

    /**
     * Test the property 'processingIssuesAvailability'
     */
    @Test
    public void processingIssuesAvailabilityTest() {
        // TODO: test processingIssuesAvailability
    }

    /**
     * Test the property 'processingProgress'
     */
    @Test
    public void processingProgressTest() {
        // TODO: test processingProgress
    }

    /**
     * Test the property 'processingStatus'
     */
    @Test
    public void processingStatusTest() {
        // TODO: test processingStatus
    }

    /**
     * Test the property 'tagSuggestionsAvailability'
     */
    @Test
    public void tagSuggestionsAvailabilityTest() {
        // TODO: test tagSuggestionsAvailability
    }

    /**
     * Test the property 'thumbnailsAvailability'
     */
    @Test
    public void thumbnailsAvailabilityTest() {
        // TODO: test thumbnailsAvailability
    }

}
