/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.DependencyUtil;
import org.openapitools.client.model.SearchListResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SearchApi
 */
@Ignore
public class SearchApiTest {

    private final SearchApi api = new SearchApi();

    
    /**
     * 
     *
     * Retrieves a list of search resources
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void youtubeSearchListTest() throws ApiException {
        List<String> part = null;
        String channelId = null;
        String channelType = null;
        String eventType = null;
        Boolean forContentOwner = null;
        Boolean forDeveloper = null;
        Boolean forMine = null;
        String location = null;
        String locationRadius = null;
        Integer maxResults = null;
        String onBehalfOfContentOwner = null;
        String order = null;
        String pageToken = null;
        String publishedAfter = null;
        String publishedBefore = null;
        String q = null;
        String regionCode = null;
        String relatedToVideoId = null;
        String relevanceLanguage = null;
        String safeSearch = null;
        String topicId = null;
        List<String> type = null;
        String videoCaption = null;
        String videoCategoryId = null;
        String videoDefinition = null;
        String videoDimension = null;
        String videoDuration = null;
        String videoEmbeddable = null;
        String videoLicense = null;
        String videoSyndicated = null;
        String videoType = null;
        SearchListResponse response = api.youtubeSearchList(part, channelId, channelType, eventType, forContentOwner, forDeveloper, forMine, location, locationRadius, maxResults, onBehalfOfContentOwner, order, pageToken, publishedAfter, publishedBefore, q, regionCode, relatedToVideoId, relevanceLanguage, safeSearch, topicId, type, videoCaption, videoCategoryId, videoDefinition, videoDimension, videoDuration, videoEmbeddable, videoLicense, videoSyndicated, videoType);

        // TODO: test validations
    }
    
}
