# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.activity_content_details_bulletin import ActivityContentDetailsBulletin
from openapi_server.models.activity_content_details_channel_item import ActivityContentDetailsChannelItem
from openapi_server.models.activity_content_details_comment import ActivityContentDetailsComment
from openapi_server.models.activity_content_details_favorite import ActivityContentDetailsFavorite
from openapi_server.models.activity_content_details_like import ActivityContentDetailsLike
from openapi_server.models.activity_content_details_playlist_item import ActivityContentDetailsPlaylistItem
from openapi_server.models.activity_content_details_promoted_item import ActivityContentDetailsPromotedItem
from openapi_server.models.activity_content_details_recommendation import ActivityContentDetailsRecommendation
from openapi_server.models.activity_content_details_social import ActivityContentDetailsSocial
from openapi_server.models.activity_content_details_subscription import ActivityContentDetailsSubscription
from openapi_server.models.activity_content_details_upload import ActivityContentDetailsUpload


class ActivityContentDetails(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ActivityContentDetails - a model defined in OpenAPI

        bulletin: The bulletin of this ActivityContentDetails [Optional].
        channel_item: The channel_item of this ActivityContentDetails [Optional].
        comment: The comment of this ActivityContentDetails [Optional].
        favorite: The favorite of this ActivityContentDetails [Optional].
        like: The like of this ActivityContentDetails [Optional].
        playlist_item: The playlist_item of this ActivityContentDetails [Optional].
        promoted_item: The promoted_item of this ActivityContentDetails [Optional].
        recommendation: The recommendation of this ActivityContentDetails [Optional].
        social: The social of this ActivityContentDetails [Optional].
        subscription: The subscription of this ActivityContentDetails [Optional].
        upload: The upload of this ActivityContentDetails [Optional].
    """

    bulletin: Optional[ActivityContentDetailsBulletin] = None
    channel_item: Optional[ActivityContentDetailsChannelItem] = None
    comment: Optional[ActivityContentDetailsComment] = None
    favorite: Optional[ActivityContentDetailsFavorite] = None
    like: Optional[ActivityContentDetailsLike] = None
    playlist_item: Optional[ActivityContentDetailsPlaylistItem] = None
    promoted_item: Optional[ActivityContentDetailsPromotedItem] = None
    recommendation: Optional[ActivityContentDetailsRecommendation] = None
    social: Optional[ActivityContentDetailsSocial] = None
    subscription: Optional[ActivityContentDetailsSubscription] = None
    upload: Optional[ActivityContentDetailsUpload] = None

ActivityContentDetails.update_forward_refs()
