# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.caption_snippet import CaptionSnippet


class Caption(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Caption - a model defined in OpenAPI

        etag: The etag of this Caption [Optional].
        id: The id of this Caption [Optional].
        kind: The kind of this Caption [Optional].
        snippet: The snippet of this Caption [Optional].
    """

    etag: Optional[str] = None
    id: Optional[str] = None
    kind: Optional[str] = None
    snippet: Optional[CaptionSnippet] = None

Caption.update_forward_refs()
