# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.ingestion_info import IngestionInfo


class CdnSettings(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CdnSettings - a model defined in OpenAPI

        format: The format of this CdnSettings [Optional].
        frame_rate: The frame_rate of this CdnSettings [Optional].
        ingestion_info: The ingestion_info of this CdnSettings [Optional].
        ingestion_type: The ingestion_type of this CdnSettings [Optional].
        resolution: The resolution of this CdnSettings [Optional].
    """

    format: Optional[str] = None
    frame_rate: Optional[str] = None
    ingestion_info: Optional[IngestionInfo] = None
    ingestion_type: Optional[str] = None
    resolution: Optional[str] = None

CdnSettings.update_forward_refs()
