# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.channel_settings import ChannelSettings
from openapi_server.models.image_settings import ImageSettings
from openapi_server.models.property_value import PropertyValue
from openapi_server.models.watch_settings import WatchSettings


class ChannelBrandingSettings(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ChannelBrandingSettings - a model defined in OpenAPI

        channel: The channel of this ChannelBrandingSettings [Optional].
        hints: The hints of this ChannelBrandingSettings [Optional].
        image: The image of this ChannelBrandingSettings [Optional].
        watch: The watch of this ChannelBrandingSettings [Optional].
    """

    channel: Optional[ChannelSettings] = None
    hints: Optional[List[PropertyValue]] = None
    image: Optional[ImageSettings] = None
    watch: Optional[WatchSettings] = None

ChannelBrandingSettings.update_forward_refs()
