# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class ChannelTopicDetails(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ChannelTopicDetails - a model defined in OpenAPI

        topic_categories: The topic_categories of this ChannelTopicDetails [Optional].
        topic_ids: The topic_ids of this ChannelTopicDetails [Optional].
    """

    topic_categories: Optional[List[str]] = None
    topic_ids: Optional[List[str]] = None

ChannelTopicDetails.update_forward_refs()
