# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class ChannelLocalization(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ChannelLocalization - a model defined in OpenAPI

        description: The description of this ChannelLocalization [Optional].
        title: The title of this ChannelLocalization [Optional].
    """

    description: Optional[str] = None
    title: Optional[str] = None

ChannelLocalization.update_forward_refs()
