# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class CommentSnippetAuthorChannelId(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CommentSnippetAuthorChannelId - a model defined in OpenAPI

        value: The value of this CommentSnippetAuthorChannelId [Optional].
    """

    value: Optional[str] = None

CommentSnippetAuthorChannelId.update_forward_refs()
