# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.comment_thread_replies import CommentThreadReplies
from openapi_server.models.comment_thread_snippet import CommentThreadSnippet


class CommentThread(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CommentThread - a model defined in OpenAPI

        etag: The etag of this CommentThread [Optional].
        id: The id of this CommentThread [Optional].
        kind: The kind of this CommentThread [Optional].
        replies: The replies of this CommentThread [Optional].
        snippet: The snippet of this CommentThread [Optional].
    """

    etag: Optional[str] = None
    id: Optional[str] = None
    kind: Optional[str] = None
    replies: Optional[CommentThreadReplies] = None
    snippet: Optional[CommentThreadSnippet] = None

CommentThread.update_forward_refs()
