# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.i18n_region import I18nRegion


class I18nRegionListResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    I18nRegionListResponse - a model defined in OpenAPI

        etag: The etag of this I18nRegionListResponse [Optional].
        event_id: The event_id of this I18nRegionListResponse [Optional].
        items: The items of this I18nRegionListResponse [Optional].
        kind: The kind of this I18nRegionListResponse [Optional].
        visitor_id: The visitor_id of this I18nRegionListResponse [Optional].
    """

    etag: Optional[str] = None
    event_id: Optional[str] = None
    items: Optional[List[I18nRegion]] = None
    kind: Optional[str] = None
    visitor_id: Optional[str] = None

I18nRegionListResponse.update_forward_refs()
