# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class IngestionInfo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    IngestionInfo - a model defined in OpenAPI

        backup_ingestion_address: The backup_ingestion_address of this IngestionInfo [Optional].
        ingestion_address: The ingestion_address of this IngestionInfo [Optional].
        rtmps_backup_ingestion_address: The rtmps_backup_ingestion_address of this IngestionInfo [Optional].
        rtmps_ingestion_address: The rtmps_ingestion_address of this IngestionInfo [Optional].
        stream_name: The stream_name of this IngestionInfo [Optional].
    """

    backup_ingestion_address: Optional[str] = None
    ingestion_address: Optional[str] = None
    rtmps_backup_ingestion_address: Optional[str] = None
    rtmps_ingestion_address: Optional[str] = None
    stream_name: Optional[str] = None

IngestionInfo.update_forward_refs()
