# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class LiveChatSuperChatDetails(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LiveChatSuperChatDetails - a model defined in OpenAPI

        amount_display_string: The amount_display_string of this LiveChatSuperChatDetails [Optional].
        amount_micros: The amount_micros of this LiveChatSuperChatDetails [Optional].
        currency: The currency of this LiveChatSuperChatDetails [Optional].
        tier: The tier of this LiveChatSuperChatDetails [Optional].
        user_comment: The user_comment of this LiveChatSuperChatDetails [Optional].
    """

    amount_display_string: Optional[str] = None
    amount_micros: Optional[str] = None
    currency: Optional[str] = None
    tier: Optional[int] = None
    user_comment: Optional[str] = None

LiveChatSuperChatDetails.update_forward_refs()
