# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class LiveBroadcastStatus(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LiveBroadcastStatus - a model defined in OpenAPI

        life_cycle_status: The life_cycle_status of this LiveBroadcastStatus [Optional].
        live_broadcast_priority: The live_broadcast_priority of this LiveBroadcastStatus [Optional].
        made_for_kids: The made_for_kids of this LiveBroadcastStatus [Optional].
        privacy_status: The privacy_status of this LiveBroadcastStatus [Optional].
        recording_status: The recording_status of this LiveBroadcastStatus [Optional].
        self_declared_made_for_kids: The self_declared_made_for_kids of this LiveBroadcastStatus [Optional].
    """

    life_cycle_status: Optional[str] = None
    live_broadcast_priority: Optional[str] = None
    made_for_kids: Optional[bool] = None
    privacy_status: Optional[str] = None
    recording_status: Optional[str] = None
    self_declared_made_for_kids: Optional[bool] = None

LiveBroadcastStatus.update_forward_refs()
