# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.live_chat_fan_funding_event_details import LiveChatFanFundingEventDetails
from openapi_server.models.live_chat_message_deleted_details import LiveChatMessageDeletedDetails
from openapi_server.models.live_chat_message_retracted_details import LiveChatMessageRetractedDetails
from openapi_server.models.live_chat_super_chat_details import LiveChatSuperChatDetails
from openapi_server.models.live_chat_super_sticker_details import LiveChatSuperStickerDetails
from openapi_server.models.live_chat_text_message_details import LiveChatTextMessageDetails
from openapi_server.models.live_chat_user_banned_message_details import LiveChatUserBannedMessageDetails


class LiveChatMessageSnippet(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LiveChatMessageSnippet - a model defined in OpenAPI

        author_channel_id: The author_channel_id of this LiveChatMessageSnippet [Optional].
        display_message: The display_message of this LiveChatMessageSnippet [Optional].
        fan_funding_event_details: The fan_funding_event_details of this LiveChatMessageSnippet [Optional].
        has_display_content: The has_display_content of this LiveChatMessageSnippet [Optional].
        live_chat_id: The live_chat_id of this LiveChatMessageSnippet [Optional].
        message_deleted_details: The message_deleted_details of this LiveChatMessageSnippet [Optional].
        message_retracted_details: The message_retracted_details of this LiveChatMessageSnippet [Optional].
        published_at: The published_at of this LiveChatMessageSnippet [Optional].
        super_chat_details: The super_chat_details of this LiveChatMessageSnippet [Optional].
        super_sticker_details: The super_sticker_details of this LiveChatMessageSnippet [Optional].
        text_message_details: The text_message_details of this LiveChatMessageSnippet [Optional].
        type: The type of this LiveChatMessageSnippet [Optional].
        user_banned_details: The user_banned_details of this LiveChatMessageSnippet [Optional].
    """

    author_channel_id: Optional[str] = None
    display_message: Optional[str] = None
    fan_funding_event_details: Optional[LiveChatFanFundingEventDetails] = None
    has_display_content: Optional[bool] = None
    live_chat_id: Optional[str] = None
    message_deleted_details: Optional[LiveChatMessageDeletedDetails] = None
    message_retracted_details: Optional[LiveChatMessageRetractedDetails] = None
    published_at: Optional[datetime] = None
    super_chat_details: Optional[LiveChatSuperChatDetails] = None
    super_sticker_details: Optional[LiveChatSuperStickerDetails] = None
    text_message_details: Optional[LiveChatTextMessageDetails] = None
    type: Optional[str] = None
    user_banned_details: Optional[LiveChatUserBannedMessageDetails] = None

LiveChatMessageSnippet.update_forward_refs()
