# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.live_chat_message_author_details import LiveChatMessageAuthorDetails
from openapi_server.models.live_chat_message_snippet import LiveChatMessageSnippet


class LiveChatMessage(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LiveChatMessage - a model defined in OpenAPI

        author_details: The author_details of this LiveChatMessage [Optional].
        etag: The etag of this LiveChatMessage [Optional].
        id: The id of this LiveChatMessage [Optional].
        kind: The kind of this LiveChatMessage [Optional].
        snippet: The snippet of this LiveChatMessage [Optional].
    """

    author_details: Optional[LiveChatMessageAuthorDetails] = None
    etag: Optional[str] = None
    id: Optional[str] = None
    kind: Optional[str] = None
    snippet: Optional[LiveChatMessageSnippet] = None

LiveChatMessage.update_forward_refs()
