# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.resource_id import ResourceId
from openapi_server.models.thumbnail_details import ThumbnailDetails


class PlaylistItemSnippet(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PlaylistItemSnippet - a model defined in OpenAPI

        channel_id: The channel_id of this PlaylistItemSnippet [Optional].
        channel_title: The channel_title of this PlaylistItemSnippet [Optional].
        description: The description of this PlaylistItemSnippet [Optional].
        playlist_id: The playlist_id of this PlaylistItemSnippet [Optional].
        position: The position of this PlaylistItemSnippet [Optional].
        published_at: The published_at of this PlaylistItemSnippet [Optional].
        resource_id: The resource_id of this PlaylistItemSnippet [Optional].
        thumbnails: The thumbnails of this PlaylistItemSnippet [Optional].
        title: The title of this PlaylistItemSnippet [Optional].
        video_owner_channel_id: The video_owner_channel_id of this PlaylistItemSnippet [Optional].
        video_owner_channel_title: The video_owner_channel_title of this PlaylistItemSnippet [Optional].
    """

    channel_id: Optional[str] = None
    channel_title: Optional[str] = None
    description: Optional[str] = None
    playlist_id: Optional[str] = None
    position: Optional[int] = None
    published_at: Optional[datetime] = None
    resource_id: Optional[ResourceId] = None
    thumbnails: Optional[ThumbnailDetails] = None
    title: Optional[str] = None
    video_owner_channel_id: Optional[str] = None
    video_owner_channel_title: Optional[str] = None

PlaylistItemSnippet.update_forward_refs()
