# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.page_info import PageInfo
from openapi_server.models.search_result import SearchResult


class SearchListResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SearchListResponse - a model defined in OpenAPI

        etag: The etag of this SearchListResponse [Optional].
        event_id: The event_id of this SearchListResponse [Optional].
        items: The items of this SearchListResponse [Optional].
        kind: The kind of this SearchListResponse [Optional].
        next_page_token: The next_page_token of this SearchListResponse [Optional].
        page_info: The page_info of this SearchListResponse [Optional].
        prev_page_token: The prev_page_token of this SearchListResponse [Optional].
        region_code: The region_code of this SearchListResponse [Optional].
        token_pagination: The token_pagination of this SearchListResponse [Optional].
        visitor_id: The visitor_id of this SearchListResponse [Optional].
    """

    etag: Optional[str] = None
    event_id: Optional[str] = None
    items: Optional[List[SearchResult]] = None
    kind: Optional[str] = None
    next_page_token: Optional[str] = None
    page_info: Optional[PageInfo] = None
    prev_page_token: Optional[str] = None
    region_code: Optional[str] = None
    token_pagination: Optional[Dict[str, Any]] = None
    visitor_id: Optional[str] = None

SearchListResponse.update_forward_refs()
