# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.channel_to_store_link_details import ChannelToStoreLinkDetails


class ThirdPartyLinkSnippet(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ThirdPartyLinkSnippet - a model defined in OpenAPI

        channel_to_store_link: The channel_to_store_link of this ThirdPartyLinkSnippet [Optional].
        type: The type of this ThirdPartyLinkSnippet [Optional].
    """

    channel_to_store_link: Optional[ChannelToStoreLinkDetails] = None
    type: Optional[str] = None

ThirdPartyLinkSnippet.update_forward_refs()
