# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.third_party_link_snippet import ThirdPartyLinkSnippet
from openapi_server.models.third_party_link_status import ThirdPartyLinkStatus


class ThirdPartyLink(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ThirdPartyLink - a model defined in OpenAPI

        etag: The etag of this ThirdPartyLink [Optional].
        kind: The kind of this ThirdPartyLink [Optional].
        linking_token: The linking_token of this ThirdPartyLink [Optional].
        snippet: The snippet of this ThirdPartyLink [Optional].
        status: The status of this ThirdPartyLink [Optional].
    """

    etag: Optional[str] = None
    kind: Optional[str] = None
    linking_token: Optional[str] = None
    snippet: Optional[ThirdPartyLinkSnippet] = None
    status: Optional[ThirdPartyLinkStatus] = None

ThirdPartyLink.update_forward_refs()
