# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class Thumbnail(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Thumbnail - a model defined in OpenAPI

        height: The height of this Thumbnail [Optional].
        url: The url of this Thumbnail [Optional].
        width: The width of this Thumbnail [Optional].
    """

    height: Optional[int] = None
    url: Optional[str] = None
    width: Optional[int] = None

Thumbnail.update_forward_refs()
