# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class VideoStatus(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    VideoStatus - a model defined in OpenAPI

        embeddable: The embeddable of this VideoStatus [Optional].
        failure_reason: The failure_reason of this VideoStatus [Optional].
        license: The license of this VideoStatus [Optional].
        made_for_kids: The made_for_kids of this VideoStatus [Optional].
        privacy_status: The privacy_status of this VideoStatus [Optional].
        public_stats_viewable: The public_stats_viewable of this VideoStatus [Optional].
        publish_at: The publish_at of this VideoStatus [Optional].
        rejection_reason: The rejection_reason of this VideoStatus [Optional].
        self_declared_made_for_kids: The self_declared_made_for_kids of this VideoStatus [Optional].
        upload_status: The upload_status of this VideoStatus [Optional].
    """

    embeddable: Optional[bool] = None
    failure_reason: Optional[str] = None
    license: Optional[str] = None
    made_for_kids: Optional[bool] = None
    privacy_status: Optional[str] = None
    public_stats_viewable: Optional[bool] = None
    publish_at: Optional[datetime] = None
    rejection_reason: Optional[str] = None
    self_declared_made_for_kids: Optional[bool] = None
    upload_status: Optional[str] = None

VideoStatus.update_forward_refs()
