# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.video_abuse_report_reason_snippet import VideoAbuseReportReasonSnippet


class VideoAbuseReportReason(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    VideoAbuseReportReason - a model defined in OpenAPI

        etag: The etag of this VideoAbuseReportReason [Optional].
        id: The id of this VideoAbuseReportReason [Optional].
        kind: The kind of this VideoAbuseReportReason [Optional].
        snippet: The snippet of this VideoAbuseReportReason [Optional].
    """

    etag: Optional[str] = None
    id: Optional[str] = None
    kind: Optional[str] = None
    snippet: Optional[VideoAbuseReportReasonSnippet] = None

VideoAbuseReportReason.update_forward_refs()
