# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.video_processing_details_processing_progress import VideoProcessingDetailsProcessingProgress


class VideoProcessingDetails(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    VideoProcessingDetails - a model defined in OpenAPI

        editor_suggestions_availability: The editor_suggestions_availability of this VideoProcessingDetails [Optional].
        file_details_availability: The file_details_availability of this VideoProcessingDetails [Optional].
        processing_failure_reason: The processing_failure_reason of this VideoProcessingDetails [Optional].
        processing_issues_availability: The processing_issues_availability of this VideoProcessingDetails [Optional].
        processing_progress: The processing_progress of this VideoProcessingDetails [Optional].
        processing_status: The processing_status of this VideoProcessingDetails [Optional].
        tag_suggestions_availability: The tag_suggestions_availability of this VideoProcessingDetails [Optional].
        thumbnails_availability: The thumbnails_availability of this VideoProcessingDetails [Optional].
    """

    editor_suggestions_availability: Optional[str] = None
    file_details_availability: Optional[str] = None
    processing_failure_reason: Optional[str] = None
    processing_issues_availability: Optional[str] = None
    processing_progress: Optional[VideoProcessingDetailsProcessingProgress] = None
    processing_status: Optional[str] = None
    tag_suggestions_availability: Optional[str] = None
    thumbnails_availability: Optional[str] = None

VideoProcessingDetails.update_forward_refs()
