# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.video_file_details_audio_stream import VideoFileDetailsAudioStream
from openapi_server.models.video_file_details_video_stream import VideoFileDetailsVideoStream


class VideoFileDetails(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    VideoFileDetails - a model defined in OpenAPI

        audio_streams: The audio_streams of this VideoFileDetails [Optional].
        bitrate_bps: The bitrate_bps of this VideoFileDetails [Optional].
        container: The container of this VideoFileDetails [Optional].
        creation_time: The creation_time of this VideoFileDetails [Optional].
        duration_ms: The duration_ms of this VideoFileDetails [Optional].
        file_name: The file_name of this VideoFileDetails [Optional].
        file_size: The file_size of this VideoFileDetails [Optional].
        file_type: The file_type of this VideoFileDetails [Optional].
        video_streams: The video_streams of this VideoFileDetails [Optional].
    """

    audio_streams: Optional[List[VideoFileDetailsAudioStream]] = None
    bitrate_bps: Optional[str] = None
    container: Optional[str] = None
    creation_time: Optional[str] = None
    duration_ms: Optional[str] = None
    file_name: Optional[str] = None
    file_size: Optional[str] = None
    file_type: Optional[str] = None
    video_streams: Optional[List[VideoFileDetailsVideoStream]] = None

VideoFileDetails.update_forward_refs()
