# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class VideoLiveStreamingDetails(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    VideoLiveStreamingDetails - a model defined in OpenAPI

        active_live_chat_id: The active_live_chat_id of this VideoLiveStreamingDetails [Optional].
        actual_end_time: The actual_end_time of this VideoLiveStreamingDetails [Optional].
        actual_start_time: The actual_start_time of this VideoLiveStreamingDetails [Optional].
        concurrent_viewers: The concurrent_viewers of this VideoLiveStreamingDetails [Optional].
        scheduled_end_time: The scheduled_end_time of this VideoLiveStreamingDetails [Optional].
        scheduled_start_time: The scheduled_start_time of this VideoLiveStreamingDetails [Optional].
    """

    active_live_chat_id: Optional[str] = None
    actual_end_time: Optional[datetime] = None
    actual_start_time: Optional[datetime] = None
    concurrent_viewers: Optional[str] = None
    scheduled_end_time: Optional[datetime] = None
    scheduled_start_time: Optional[datetime] = None

VideoLiveStreamingDetails.update_forward_refs()
