# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class VideoAbuseReport(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    VideoAbuseReport - a model defined in OpenAPI

        comments: The comments of this VideoAbuseReport [Optional].
        language: The language of this VideoAbuseReport [Optional].
        reason_id: The reason_id of this VideoAbuseReport [Optional].
        secondary_reason_id: The secondary_reason_id of this VideoAbuseReport [Optional].
        video_id: The video_id of this VideoAbuseReport [Optional].
    """

    comments: Optional[str] = None
    language: Optional[str] = None
    reason_id: Optional[str] = None
    secondary_reason_id: Optional[str] = None
    video_id: Optional[str] = None

VideoAbuseReport.update_forward_refs()
