# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class VideoContentDetailsRegionRestriction(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    VideoContentDetailsRegionRestriction - a model defined in OpenAPI

        allowed: The allowed of this VideoContentDetailsRegionRestriction [Optional].
        blocked: The blocked of this VideoContentDetailsRegionRestriction [Optional].
    """

    allowed: Optional[List[str]] = None
    blocked: Optional[List[str]] = None

VideoContentDetailsRegionRestriction.update_forward_refs()
