# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.video_abuse_report_secondary_reason import VideoAbuseReportSecondaryReason


class VideoAbuseReportReasonSnippet(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    VideoAbuseReportReasonSnippet - a model defined in OpenAPI

        label: The label of this VideoAbuseReportReasonSnippet [Optional].
        secondary_reasons: The secondary_reasons of this VideoAbuseReportReasonSnippet [Optional].
    """

    label: Optional[str] = None
    secondary_reasons: Optional[List[VideoAbuseReportSecondaryReason]] = None

VideoAbuseReportReasonSnippet.update_forward_refs()
