# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class VideoCategorySnippet(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    VideoCategorySnippet - a model defined in OpenAPI

        assignable: The assignable of this VideoCategorySnippet [Optional].
        channel_id: The channel_id of this VideoCategorySnippet [Optional].
        title: The title of this VideoCategorySnippet [Optional].
    """

    assignable: Optional[bool] = None
    channel_id: Optional[str] = None
    title: Optional[str] = None

VideoCategorySnippet.update_forward_refs()
