# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class VideoFileDetailsAudioStream(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    VideoFileDetailsAudioStream - a model defined in OpenAPI

        bitrate_bps: The bitrate_bps of this VideoFileDetailsAudioStream [Optional].
        channel_count: The channel_count of this VideoFileDetailsAudioStream [Optional].
        codec: The codec of this VideoFileDetailsAudioStream [Optional].
        vendor: The vendor of this VideoFileDetailsAudioStream [Optional].
    """

    bitrate_bps: Optional[str] = None
    channel_count: Optional[int] = None
    codec: Optional[str] = None
    vendor: Optional[str] = None

VideoFileDetailsAudioStream.update_forward_refs()
