# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class WatchSettings(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    WatchSettings - a model defined in OpenAPI

        background_color: The background_color of this WatchSettings [Optional].
        featured_playlist_id: The featured_playlist_id of this WatchSettings [Optional].
        text_color: The text_color of this WatchSettings [Optional].
    """

    background_color: Optional[str] = None
    featured_playlist_id: Optional[str] = None
    text_color: Optional[str] = None

WatchSettings.update_forward_refs()
