/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ActivityContentDetailsBulletin;
import org.openapitools.client.model.ActivityContentDetailsChannelItem;
import org.openapitools.client.model.ActivityContentDetailsComment;
import org.openapitools.client.model.ActivityContentDetailsFavorite;
import org.openapitools.client.model.ActivityContentDetailsLike;
import org.openapitools.client.model.ActivityContentDetailsPlaylistItem;
import org.openapitools.client.model.ActivityContentDetailsPromotedItem;
import org.openapitools.client.model.ActivityContentDetailsRecommendation;
import org.openapitools.client.model.ActivityContentDetailsSocial;
import org.openapitools.client.model.ActivityContentDetailsSubscription;
import org.openapitools.client.model.ActivityContentDetailsUpload;

/**
 * Details about the content of an activity: the video that was shared, the channel that was subscribed to, etc.
 */
@ApiModel(description = "Details about the content of an activity: the video that was shared, the channel that was subscribed to, etc.")
@javax.annotation.Generated(value = "com.us.idl.javaidl.JavaIDLCodegen", date = "2021-08-24T20:55:04.712703200+02:00[Europe/Paris]")
public class ActivityContentDetails {
  public static final String SERIALIZED_NAME_BULLETIN = "bulletin";
  @SerializedName(SERIALIZED_NAME_BULLETIN)
  private ActivityContentDetailsBulletin bulletin;

  public static final String SERIALIZED_NAME_CHANNEL_ITEM = "channelItem";
  @SerializedName(SERIALIZED_NAME_CHANNEL_ITEM)
  private ActivityContentDetailsChannelItem channelItem;

  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  private ActivityContentDetailsComment comment;

  public static final String SERIALIZED_NAME_FAVORITE = "favorite";
  @SerializedName(SERIALIZED_NAME_FAVORITE)
  private ActivityContentDetailsFavorite favorite;

  public static final String SERIALIZED_NAME_LIKE = "like";
  @SerializedName(SERIALIZED_NAME_LIKE)
  private ActivityContentDetailsLike like;

  public static final String SERIALIZED_NAME_PLAYLIST_ITEM = "playlistItem";
  @SerializedName(SERIALIZED_NAME_PLAYLIST_ITEM)
  private ActivityContentDetailsPlaylistItem playlistItem;

  public static final String SERIALIZED_NAME_PROMOTED_ITEM = "promotedItem";
  @SerializedName(SERIALIZED_NAME_PROMOTED_ITEM)
  private ActivityContentDetailsPromotedItem promotedItem;

  public static final String SERIALIZED_NAME_RECOMMENDATION = "recommendation";
  @SerializedName(SERIALIZED_NAME_RECOMMENDATION)
  private ActivityContentDetailsRecommendation recommendation;

  public static final String SERIALIZED_NAME_SOCIAL = "social";
  @SerializedName(SERIALIZED_NAME_SOCIAL)
  private ActivityContentDetailsSocial social;

  public static final String SERIALIZED_NAME_SUBSCRIPTION = "subscription";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION)
  private ActivityContentDetailsSubscription subscription;

  public static final String SERIALIZED_NAME_UPLOAD = "upload";
  @SerializedName(SERIALIZED_NAME_UPLOAD)
  private ActivityContentDetailsUpload upload;


  public ActivityContentDetails bulletin(ActivityContentDetailsBulletin bulletin) {
    
    this.bulletin = bulletin;
    return this;
  }

   /**
   * Get bulletin
   * @return bulletin
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ActivityContentDetailsBulletin getBulletin() {
    return bulletin;
  }


  public void setBulletin(ActivityContentDetailsBulletin bulletin) {
    this.bulletin = bulletin;
  }


  public ActivityContentDetails channelItem(ActivityContentDetailsChannelItem channelItem) {
    
    this.channelItem = channelItem;
    return this;
  }

   /**
   * Get channelItem
   * @return channelItem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ActivityContentDetailsChannelItem getChannelItem() {
    return channelItem;
  }


  public void setChannelItem(ActivityContentDetailsChannelItem channelItem) {
    this.channelItem = channelItem;
  }


  public ActivityContentDetails comment(ActivityContentDetailsComment comment) {
    
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ActivityContentDetailsComment getComment() {
    return comment;
  }


  public void setComment(ActivityContentDetailsComment comment) {
    this.comment = comment;
  }


  public ActivityContentDetails favorite(ActivityContentDetailsFavorite favorite) {
    
    this.favorite = favorite;
    return this;
  }

   /**
   * Get favorite
   * @return favorite
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ActivityContentDetailsFavorite getFavorite() {
    return favorite;
  }


  public void setFavorite(ActivityContentDetailsFavorite favorite) {
    this.favorite = favorite;
  }


  public ActivityContentDetails like(ActivityContentDetailsLike like) {
    
    this.like = like;
    return this;
  }

   /**
   * Get like
   * @return like
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ActivityContentDetailsLike getLike() {
    return like;
  }


  public void setLike(ActivityContentDetailsLike like) {
    this.like = like;
  }


  public ActivityContentDetails playlistItem(ActivityContentDetailsPlaylistItem playlistItem) {
    
    this.playlistItem = playlistItem;
    return this;
  }

   /**
   * Get playlistItem
   * @return playlistItem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ActivityContentDetailsPlaylistItem getPlaylistItem() {
    return playlistItem;
  }


  public void setPlaylistItem(ActivityContentDetailsPlaylistItem playlistItem) {
    this.playlistItem = playlistItem;
  }


  public ActivityContentDetails promotedItem(ActivityContentDetailsPromotedItem promotedItem) {
    
    this.promotedItem = promotedItem;
    return this;
  }

   /**
   * Get promotedItem
   * @return promotedItem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ActivityContentDetailsPromotedItem getPromotedItem() {
    return promotedItem;
  }


  public void setPromotedItem(ActivityContentDetailsPromotedItem promotedItem) {
    this.promotedItem = promotedItem;
  }


  public ActivityContentDetails recommendation(ActivityContentDetailsRecommendation recommendation) {
    
    this.recommendation = recommendation;
    return this;
  }

   /**
   * Get recommendation
   * @return recommendation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ActivityContentDetailsRecommendation getRecommendation() {
    return recommendation;
  }


  public void setRecommendation(ActivityContentDetailsRecommendation recommendation) {
    this.recommendation = recommendation;
  }


  public ActivityContentDetails social(ActivityContentDetailsSocial social) {
    
    this.social = social;
    return this;
  }

   /**
   * Get social
   * @return social
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ActivityContentDetailsSocial getSocial() {
    return social;
  }


  public void setSocial(ActivityContentDetailsSocial social) {
    this.social = social;
  }


  public ActivityContentDetails subscription(ActivityContentDetailsSubscription subscription) {
    
    this.subscription = subscription;
    return this;
  }

   /**
   * Get subscription
   * @return subscription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ActivityContentDetailsSubscription getSubscription() {
    return subscription;
  }


  public void setSubscription(ActivityContentDetailsSubscription subscription) {
    this.subscription = subscription;
  }


  public ActivityContentDetails upload(ActivityContentDetailsUpload upload) {
    
    this.upload = upload;
    return this;
  }

   /**
   * Get upload
   * @return upload
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ActivityContentDetailsUpload getUpload() {
    return upload;
  }


  public void setUpload(ActivityContentDetailsUpload upload) {
    this.upload = upload;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivityContentDetails activityContentDetails = (ActivityContentDetails) o;
    return Objects.equals(this.bulletin, activityContentDetails.bulletin) &&
        Objects.equals(this.channelItem, activityContentDetails.channelItem) &&
        Objects.equals(this.comment, activityContentDetails.comment) &&
        Objects.equals(this.favorite, activityContentDetails.favorite) &&
        Objects.equals(this.like, activityContentDetails.like) &&
        Objects.equals(this.playlistItem, activityContentDetails.playlistItem) &&
        Objects.equals(this.promotedItem, activityContentDetails.promotedItem) &&
        Objects.equals(this.recommendation, activityContentDetails.recommendation) &&
        Objects.equals(this.social, activityContentDetails.social) &&
        Objects.equals(this.subscription, activityContentDetails.subscription) &&
        Objects.equals(this.upload, activityContentDetails.upload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bulletin, channelItem, comment, favorite, like, playlistItem, promotedItem, recommendation, social, subscription, upload);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivityContentDetails {\n");
    sb.append("    bulletin: ").append(toIndentedString(bulletin)).append("\n");
    sb.append("    channelItem: ").append(toIndentedString(channelItem)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    favorite: ").append(toIndentedString(favorite)).append("\n");
    sb.append("    like: ").append(toIndentedString(like)).append("\n");
    sb.append("    playlistItem: ").append(toIndentedString(playlistItem)).append("\n");
    sb.append("    promotedItem: ").append(toIndentedString(promotedItem)).append("\n");
    sb.append("    recommendation: ").append(toIndentedString(recommendation)).append("\n");
    sb.append("    social: ").append(toIndentedString(social)).append("\n");
    sb.append("    subscription: ").append(toIndentedString(subscription)).append("\n");
    sb.append("    upload: ").append(toIndentedString(upload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

