/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ResourceId;

/**
 * Details about a social network post.
 */
@ApiModel(description = "Details about a social network post.")
@javax.annotation.Generated(value = "com.us.idl.javaidl.JavaIDLCodegen", date = "2021-08-24T20:55:04.712703200+02:00[Europe/Paris]")
public class ActivityContentDetailsSocial {
  public static final String SERIALIZED_NAME_AUTHOR = "author";
  @SerializedName(SERIALIZED_NAME_AUTHOR)
  private String author;

  public static final String SERIALIZED_NAME_IMAGE_URL = "imageUrl";
  @SerializedName(SERIALIZED_NAME_IMAGE_URL)
  private String imageUrl;

  public static final String SERIALIZED_NAME_REFERENCE_URL = "referenceUrl";
  @SerializedName(SERIALIZED_NAME_REFERENCE_URL)
  private String referenceUrl;

  public static final String SERIALIZED_NAME_RESOURCE_ID = "resourceId";
  @SerializedName(SERIALIZED_NAME_RESOURCE_ID)
  private ResourceId resourceId;

  /**
   * The name of the social network.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    TYPEUNSPECIFIED("typeUnspecified"),
    
    GOOGLEPLUS("googlePlus"),
    
    FACEBOOK("facebook"),
    
    TWITTER("twitter");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;


  public ActivityContentDetailsSocial author(String author) {
    
    this.author = author;
    return this;
  }

   /**
   * The author of the social network post.
   * @return author
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The author of the social network post.")

  public String getAuthor() {
    return author;
  }


  public void setAuthor(String author) {
    this.author = author;
  }


  public ActivityContentDetailsSocial imageUrl(String imageUrl) {
    
    this.imageUrl = imageUrl;
    return this;
  }

   /**
   * An image of the post&#39;s author.
   * @return imageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An image of the post's author.")

  public String getImageUrl() {
    return imageUrl;
  }


  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }


  public ActivityContentDetailsSocial referenceUrl(String referenceUrl) {
    
    this.referenceUrl = referenceUrl;
    return this;
  }

   /**
   * The URL of the social network post.
   * @return referenceUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The URL of the social network post.")

  public String getReferenceUrl() {
    return referenceUrl;
  }


  public void setReferenceUrl(String referenceUrl) {
    this.referenceUrl = referenceUrl;
  }


  public ActivityContentDetailsSocial resourceId(ResourceId resourceId) {
    
    this.resourceId = resourceId;
    return this;
  }

   /**
   * Get resourceId
   * @return resourceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ResourceId getResourceId() {
    return resourceId;
  }


  public void setResourceId(ResourceId resourceId) {
    this.resourceId = resourceId;
  }


  public ActivityContentDetailsSocial type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * The name of the social network.
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the social network.")

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivityContentDetailsSocial activityContentDetailsSocial = (ActivityContentDetailsSocial) o;
    return Objects.equals(this.author, activityContentDetailsSocial.author) &&
        Objects.equals(this.imageUrl, activityContentDetailsSocial.imageUrl) &&
        Objects.equals(this.referenceUrl, activityContentDetailsSocial.referenceUrl) &&
        Objects.equals(this.resourceId, activityContentDetailsSocial.resourceId) &&
        Objects.equals(this.type, activityContentDetailsSocial.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(author, imageUrl, referenceUrl, resourceId, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivityContentDetailsSocial {\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("    referenceUrl: ").append(toIndentedString(referenceUrl)).append("\n");
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

