/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.IngestionInfo;

/**
 * Brief description of the live stream cdn settings.
 */
@ApiModel(description = "Brief description of the live stream cdn settings.")
@javax.annotation.Generated(value = "com.us.idl.javaidl.JavaIDLCodegen", date = "2021-08-24T20:55:04.712703200+02:00[Europe/Paris]")
public class CdnSettings {
  public static final String SERIALIZED_NAME_FORMAT = "format";
  @SerializedName(SERIALIZED_NAME_FORMAT)
  private String format;

  /**
   * The frame rate of the inbound video data.
   */
  @JsonAdapter(FrameRateEnum.Adapter.class)
  public enum FrameRateEnum {
    _30FPS("30fps"),
    
    _60FPS("60fps"),
    
    VARIABLE("variable");

    private String value;

    FrameRateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FrameRateEnum fromValue(String value) {
      for (FrameRateEnum b : FrameRateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<FrameRateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FrameRateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FrameRateEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return FrameRateEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_FRAME_RATE = "frameRate";
  @SerializedName(SERIALIZED_NAME_FRAME_RATE)
  private FrameRateEnum frameRate;

  public static final String SERIALIZED_NAME_INGESTION_INFO = "ingestionInfo";
  @SerializedName(SERIALIZED_NAME_INGESTION_INFO)
  private IngestionInfo ingestionInfo;

  /**
   *  The method or protocol used to transmit the video stream.
   */
  @JsonAdapter(IngestionTypeEnum.Adapter.class)
  public enum IngestionTypeEnum {
    RTMP("rtmp"),
    
    DASH("dash"),
    
    WEBRTC("webrtc"),
    
    HLS("hls");

    private String value;

    IngestionTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static IngestionTypeEnum fromValue(String value) {
      for (IngestionTypeEnum b : IngestionTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<IngestionTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final IngestionTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public IngestionTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return IngestionTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_INGESTION_TYPE = "ingestionType";
  @SerializedName(SERIALIZED_NAME_INGESTION_TYPE)
  private IngestionTypeEnum ingestionType;

  /**
   * The resolution of the inbound video data.
   */
  @JsonAdapter(ResolutionEnum.Adapter.class)
  public enum ResolutionEnum {
    _240P("240p"),
    
    _360P("360p"),
    
    _480P("480p"),
    
    _720P("720p"),
    
    _1080P("1080p"),
    
    _1440P("1440p"),
    
    _2160P("2160p"),
    
    VARIABLE("variable");

    private String value;

    ResolutionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ResolutionEnum fromValue(String value) {
      for (ResolutionEnum b : ResolutionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ResolutionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ResolutionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ResolutionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ResolutionEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_RESOLUTION = "resolution";
  @SerializedName(SERIALIZED_NAME_RESOLUTION)
  private ResolutionEnum resolution;


  public CdnSettings format(String format) {
    
    this.format = format;
    return this;
  }

   /**
   * The format of the video stream that you are sending to Youtube. 
   * @return format
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The format of the video stream that you are sending to Youtube. ")

  public String getFormat() {
    return format;
  }


  public void setFormat(String format) {
    this.format = format;
  }


  public CdnSettings frameRate(FrameRateEnum frameRate) {
    
    this.frameRate = frameRate;
    return this;
  }

   /**
   * The frame rate of the inbound video data.
   * @return frameRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The frame rate of the inbound video data.")

  public FrameRateEnum getFrameRate() {
    return frameRate;
  }


  public void setFrameRate(FrameRateEnum frameRate) {
    this.frameRate = frameRate;
  }


  public CdnSettings ingestionInfo(IngestionInfo ingestionInfo) {
    
    this.ingestionInfo = ingestionInfo;
    return this;
  }

   /**
   * Get ingestionInfo
   * @return ingestionInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public IngestionInfo getIngestionInfo() {
    return ingestionInfo;
  }


  public void setIngestionInfo(IngestionInfo ingestionInfo) {
    this.ingestionInfo = ingestionInfo;
  }


  public CdnSettings ingestionType(IngestionTypeEnum ingestionType) {
    
    this.ingestionType = ingestionType;
    return this;
  }

   /**
   *  The method or protocol used to transmit the video stream.
   * @return ingestionType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = " The method or protocol used to transmit the video stream.")

  public IngestionTypeEnum getIngestionType() {
    return ingestionType;
  }


  public void setIngestionType(IngestionTypeEnum ingestionType) {
    this.ingestionType = ingestionType;
  }


  public CdnSettings resolution(ResolutionEnum resolution) {
    
    this.resolution = resolution;
    return this;
  }

   /**
   * The resolution of the inbound video data.
   * @return resolution
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The resolution of the inbound video data.")

  public ResolutionEnum getResolution() {
    return resolution;
  }


  public void setResolution(ResolutionEnum resolution) {
    this.resolution = resolution;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CdnSettings cdnSettings = (CdnSettings) o;
    return Objects.equals(this.format, cdnSettings.format) &&
        Objects.equals(this.frameRate, cdnSettings.frameRate) &&
        Objects.equals(this.ingestionInfo, cdnSettings.ingestionInfo) &&
        Objects.equals(this.ingestionType, cdnSettings.ingestionType) &&
        Objects.equals(this.resolution, cdnSettings.resolution);
  }

  @Override
  public int hashCode() {
    return Objects.hash(format, frameRate, ingestionInfo, ingestionType, resolution);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CdnSettings {\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    frameRate: ").append(toIndentedString(frameRate)).append("\n");
    sb.append("    ingestionInfo: ").append(toIndentedString(ingestionInfo)).append("\n");
    sb.append("    ingestionType: ").append(toIndentedString(ingestionType)).append("\n");
    sb.append("    resolution: ").append(toIndentedString(resolution)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

