/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Information specific to a store on a merchandising platform linked to a YouTube channel.
 */
@ApiModel(description = "Information specific to a store on a merchandising platform linked to a YouTube channel.")
@javax.annotation.Generated(value = "com.us.idl.javaidl.JavaIDLCodegen", date = "2021-08-24T20:55:04.712703200+02:00[Europe/Paris]")
public class ChannelToStoreLinkDetails {
  public static final String SERIALIZED_NAME_STORE_NAME = "storeName";
  @SerializedName(SERIALIZED_NAME_STORE_NAME)
  private String storeName;

  public static final String SERIALIZED_NAME_STORE_URL = "storeUrl";
  @SerializedName(SERIALIZED_NAME_STORE_URL)
  private String storeUrl;


  public ChannelToStoreLinkDetails storeName(String storeName) {
    
    this.storeName = storeName;
    return this;
  }

   /**
   * Name of the store.
   * @return storeName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the store.")

  public String getStoreName() {
    return storeName;
  }


  public void setStoreName(String storeName) {
    this.storeName = storeName;
  }


  public ChannelToStoreLinkDetails storeUrl(String storeUrl) {
    
    this.storeUrl = storeUrl;
    return this;
  }

   /**
   * Landing page of the store.
   * @return storeUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Landing page of the store.")

  public String getStoreUrl() {
    return storeUrl;
  }


  public void setStoreUrl(String storeUrl) {
    this.storeUrl = storeUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelToStoreLinkDetails channelToStoreLinkDetails = (ChannelToStoreLinkDetails) o;
    return Objects.equals(this.storeName, channelToStoreLinkDetails.storeName) &&
        Objects.equals(this.storeUrl, channelToStoreLinkDetails.storeUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(storeName, storeUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelToStoreLinkDetails {\n");
    sb.append("    storeName: ").append(toIndentedString(storeName)).append("\n");
    sb.append("    storeUrl: ").append(toIndentedString(storeUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

