/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The auditDetails object encapsulates channel data that is relevant for YouTube Partners during the audit process.
 */
@ApiModel(description = "The auditDetails object encapsulates channel data that is relevant for YouTube Partners during the audit process.")
@javax.annotation.Generated(value = "com.us.idl.javaidl.JavaIDLCodegen", date = "2021-08-24T20:55:04.712703200+02:00[Europe/Paris]")
public class ChannelAuditDetails {
  public static final String SERIALIZED_NAME_COMMUNITY_GUIDELINES_GOOD_STANDING = "communityGuidelinesGoodStanding";
  @SerializedName(SERIALIZED_NAME_COMMUNITY_GUIDELINES_GOOD_STANDING)
  private Boolean communityGuidelinesGoodStanding;

  public static final String SERIALIZED_NAME_CONTENT_ID_CLAIMS_GOOD_STANDING = "contentIdClaimsGoodStanding";
  @SerializedName(SERIALIZED_NAME_CONTENT_ID_CLAIMS_GOOD_STANDING)
  private Boolean contentIdClaimsGoodStanding;

  public static final String SERIALIZED_NAME_COPYRIGHT_STRIKES_GOOD_STANDING = "copyrightStrikesGoodStanding";
  @SerializedName(SERIALIZED_NAME_COPYRIGHT_STRIKES_GOOD_STANDING)
  private Boolean copyrightStrikesGoodStanding;


  public ChannelAuditDetails communityGuidelinesGoodStanding(Boolean communityGuidelinesGoodStanding) {
    
    this.communityGuidelinesGoodStanding = communityGuidelinesGoodStanding;
    return this;
  }

   /**
   * Whether or not the channel respects the community guidelines.
   * @return communityGuidelinesGoodStanding
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether or not the channel respects the community guidelines.")

  public Boolean getCommunityGuidelinesGoodStanding() {
    return communityGuidelinesGoodStanding;
  }


  public void setCommunityGuidelinesGoodStanding(Boolean communityGuidelinesGoodStanding) {
    this.communityGuidelinesGoodStanding = communityGuidelinesGoodStanding;
  }


  public ChannelAuditDetails contentIdClaimsGoodStanding(Boolean contentIdClaimsGoodStanding) {
    
    this.contentIdClaimsGoodStanding = contentIdClaimsGoodStanding;
    return this;
  }

   /**
   * Whether or not the channel has any unresolved claims.
   * @return contentIdClaimsGoodStanding
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether or not the channel has any unresolved claims.")

  public Boolean getContentIdClaimsGoodStanding() {
    return contentIdClaimsGoodStanding;
  }


  public void setContentIdClaimsGoodStanding(Boolean contentIdClaimsGoodStanding) {
    this.contentIdClaimsGoodStanding = contentIdClaimsGoodStanding;
  }


  public ChannelAuditDetails copyrightStrikesGoodStanding(Boolean copyrightStrikesGoodStanding) {
    
    this.copyrightStrikesGoodStanding = copyrightStrikesGoodStanding;
    return this;
  }

   /**
   * Whether or not the channel has any copyright strikes.
   * @return copyrightStrikesGoodStanding
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether or not the channel has any copyright strikes.")

  public Boolean getCopyrightStrikesGoodStanding() {
    return copyrightStrikesGoodStanding;
  }


  public void setCopyrightStrikesGoodStanding(Boolean copyrightStrikesGoodStanding) {
    this.copyrightStrikesGoodStanding = copyrightStrikesGoodStanding;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelAuditDetails channelAuditDetails = (ChannelAuditDetails) o;
    return Objects.equals(this.communityGuidelinesGoodStanding, channelAuditDetails.communityGuidelinesGoodStanding) &&
        Objects.equals(this.contentIdClaimsGoodStanding, channelAuditDetails.contentIdClaimsGoodStanding) &&
        Objects.equals(this.copyrightStrikesGoodStanding, channelAuditDetails.copyrightStrikesGoodStanding);
  }

  @Override
  public int hashCode() {
    return Objects.hash(communityGuidelinesGoodStanding, contentIdClaimsGoodStanding, copyrightStrikesGoodStanding);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelAuditDetails {\n");
    sb.append("    communityGuidelinesGoodStanding: ").append(toIndentedString(communityGuidelinesGoodStanding)).append("\n");
    sb.append("    contentIdClaimsGoodStanding: ").append(toIndentedString(contentIdClaimsGoodStanding)).append("\n");
    sb.append("    copyrightStrikesGoodStanding: ").append(toIndentedString(copyrightStrikesGoodStanding)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

