/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * JSON template for the status part of a channel.
 */
@ApiModel(description = "JSON template for the status part of a channel.")
@javax.annotation.Generated(value = "com.us.idl.javaidl.JavaIDLCodegen", date = "2021-08-24T20:55:04.712703200+02:00[Europe/Paris]")
public class ChannelStatus {
  public static final String SERIALIZED_NAME_IS_LINKED = "isLinked";
  @SerializedName(SERIALIZED_NAME_IS_LINKED)
  private Boolean isLinked;

  /**
   * The long uploads status of this channel. See https://support.google.com/youtube/answer/71673 for more information.
   */
  @JsonAdapter(LongUploadsStatusEnum.Adapter.class)
  public enum LongUploadsStatusEnum {
    LONGUPLOADSUNSPECIFIED("longUploadsUnspecified"),
    
    ALLOWED("allowed"),
    
    ELIGIBLE("eligible"),
    
    DISALLOWED("disallowed");

    private String value;

    LongUploadsStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static LongUploadsStatusEnum fromValue(String value) {
      for (LongUploadsStatusEnum b : LongUploadsStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<LongUploadsStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LongUploadsStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public LongUploadsStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return LongUploadsStatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_LONG_UPLOADS_STATUS = "longUploadsStatus";
  @SerializedName(SERIALIZED_NAME_LONG_UPLOADS_STATUS)
  private LongUploadsStatusEnum longUploadsStatus;

  public static final String SERIALIZED_NAME_MADE_FOR_KIDS = "madeForKids";
  @SerializedName(SERIALIZED_NAME_MADE_FOR_KIDS)
  private Boolean madeForKids;

  /**
   * Privacy status of the channel.
   */
  @JsonAdapter(PrivacyStatusEnum.Adapter.class)
  public enum PrivacyStatusEnum {
    PUBLIC("public"),
    
    UNLISTED("unlisted"),
    
    PRIVATE("private");

    private String value;

    PrivacyStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PrivacyStatusEnum fromValue(String value) {
      for (PrivacyStatusEnum b : PrivacyStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PrivacyStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PrivacyStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PrivacyStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PrivacyStatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_PRIVACY_STATUS = "privacyStatus";
  @SerializedName(SERIALIZED_NAME_PRIVACY_STATUS)
  private PrivacyStatusEnum privacyStatus;

  public static final String SERIALIZED_NAME_SELF_DECLARED_MADE_FOR_KIDS = "selfDeclaredMadeForKids";
  @SerializedName(SERIALIZED_NAME_SELF_DECLARED_MADE_FOR_KIDS)
  private Boolean selfDeclaredMadeForKids;


  public ChannelStatus isLinked(Boolean isLinked) {
    
    this.isLinked = isLinked;
    return this;
  }

   /**
   * If true, then the user is linked to either a YouTube username or G+ account. Otherwise, the user doesn&#39;t have a public YouTube identity.
   * @return isLinked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If true, then the user is linked to either a YouTube username or G+ account. Otherwise, the user doesn't have a public YouTube identity.")

  public Boolean getIsLinked() {
    return isLinked;
  }


  public void setIsLinked(Boolean isLinked) {
    this.isLinked = isLinked;
  }


  public ChannelStatus longUploadsStatus(LongUploadsStatusEnum longUploadsStatus) {
    
    this.longUploadsStatus = longUploadsStatus;
    return this;
  }

   /**
   * The long uploads status of this channel. See https://support.google.com/youtube/answer/71673 for more information.
   * @return longUploadsStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The long uploads status of this channel. See https://support.google.com/youtube/answer/71673 for more information.")

  public LongUploadsStatusEnum getLongUploadsStatus() {
    return longUploadsStatus;
  }


  public void setLongUploadsStatus(LongUploadsStatusEnum longUploadsStatus) {
    this.longUploadsStatus = longUploadsStatus;
  }


  public ChannelStatus madeForKids(Boolean madeForKids) {
    
    this.madeForKids = madeForKids;
    return this;
  }

   /**
   * Get madeForKids
   * @return madeForKids
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getMadeForKids() {
    return madeForKids;
  }


  public void setMadeForKids(Boolean madeForKids) {
    this.madeForKids = madeForKids;
  }


  public ChannelStatus privacyStatus(PrivacyStatusEnum privacyStatus) {
    
    this.privacyStatus = privacyStatus;
    return this;
  }

   /**
   * Privacy status of the channel.
   * @return privacyStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Privacy status of the channel.")

  public PrivacyStatusEnum getPrivacyStatus() {
    return privacyStatus;
  }


  public void setPrivacyStatus(PrivacyStatusEnum privacyStatus) {
    this.privacyStatus = privacyStatus;
  }


  public ChannelStatus selfDeclaredMadeForKids(Boolean selfDeclaredMadeForKids) {
    
    this.selfDeclaredMadeForKids = selfDeclaredMadeForKids;
    return this;
  }

   /**
   * Get selfDeclaredMadeForKids
   * @return selfDeclaredMadeForKids
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getSelfDeclaredMadeForKids() {
    return selfDeclaredMadeForKids;
  }


  public void setSelfDeclaredMadeForKids(Boolean selfDeclaredMadeForKids) {
    this.selfDeclaredMadeForKids = selfDeclaredMadeForKids;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelStatus channelStatus = (ChannelStatus) o;
    return Objects.equals(this.isLinked, channelStatus.isLinked) &&
        Objects.equals(this.longUploadsStatus, channelStatus.longUploadsStatus) &&
        Objects.equals(this.madeForKids, channelStatus.madeForKids) &&
        Objects.equals(this.privacyStatus, channelStatus.privacyStatus) &&
        Objects.equals(this.selfDeclaredMadeForKids, channelStatus.selfDeclaredMadeForKids);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isLinked, longUploadsStatus, madeForKids, privacyStatus, selfDeclaredMadeForKids);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelStatus {\n");
    sb.append("    isLinked: ").append(toIndentedString(isLinked)).append("\n");
    sb.append("    longUploadsStatus: ").append(toIndentedString(longUploadsStatus)).append("\n");
    sb.append("    madeForKids: ").append(toIndentedString(madeForKids)).append("\n");
    sb.append("    privacyStatus: ").append(toIndentedString(privacyStatus)).append("\n");
    sb.append("    selfDeclaredMadeForKids: ").append(toIndentedString(selfDeclaredMadeForKids)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

