/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ChannelSettings;
import org.openapitools.client.model.ImageSettings;
import org.openapitools.client.model.PropertyValue;
import org.openapitools.client.model.WatchSettings;

/**
 * Branding properties of a YouTube channel.
 */
@ApiModel(description = "Branding properties of a YouTube channel.")
@javax.annotation.Generated(value = "com.us.idl.javaidl.JavaIDLCodegen", date = "2021-08-24T20:55:04.712703200+02:00[Europe/Paris]")
public class ChannelBrandingSettings {
  public static final String SERIALIZED_NAME_CHANNEL = "channel";
  @SerializedName(SERIALIZED_NAME_CHANNEL)
  private ChannelSettings channel;

  public static final String SERIALIZED_NAME_HINTS = "hints";
  @SerializedName(SERIALIZED_NAME_HINTS)
  private List<PropertyValue> hints = null;

  public static final String SERIALIZED_NAME_IMAGE = "image";
  @SerializedName(SERIALIZED_NAME_IMAGE)
  private ImageSettings image;

  public static final String SERIALIZED_NAME_WATCH = "watch";
  @SerializedName(SERIALIZED_NAME_WATCH)
  private WatchSettings watch;


  public ChannelBrandingSettings channel(ChannelSettings channel) {
    
    this.channel = channel;
    return this;
  }

   /**
   * Get channel
   * @return channel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ChannelSettings getChannel() {
    return channel;
  }


  public void setChannel(ChannelSettings channel) {
    this.channel = channel;
  }


  public ChannelBrandingSettings hints(List<PropertyValue> hints) {
    
    this.hints = hints;
    return this;
  }

  public ChannelBrandingSettings addHintsItem(PropertyValue hintsItem) {
    if (this.hints == null) {
      this.hints = new ArrayList<PropertyValue>();
    }
    this.hints.add(hintsItem);
    return this;
  }

   /**
   * Additional experimental branding properties.
   * @return hints
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Additional experimental branding properties.")

  public List<PropertyValue> getHints() {
    return hints;
  }


  public void setHints(List<PropertyValue> hints) {
    this.hints = hints;
  }


  public ChannelBrandingSettings image(ImageSettings image) {
    
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ImageSettings getImage() {
    return image;
  }


  public void setImage(ImageSettings image) {
    this.image = image;
  }


  public ChannelBrandingSettings watch(WatchSettings watch) {
    
    this.watch = watch;
    return this;
  }

   /**
   * Get watch
   * @return watch
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WatchSettings getWatch() {
    return watch;
  }


  public void setWatch(WatchSettings watch) {
    this.watch = watch;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelBrandingSettings channelBrandingSettings = (ChannelBrandingSettings) o;
    return Objects.equals(this.channel, channelBrandingSettings.channel) &&
        Objects.equals(this.hints, channelBrandingSettings.hints) &&
        Objects.equals(this.image, channelBrandingSettings.image) &&
        Objects.equals(this.watch, channelBrandingSettings.watch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, hints, image, watch);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelBrandingSettings {\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    hints: ").append(toIndentedString(hints)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    watch: ").append(toIndentedString(watch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

