/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.LocalizedProperty;

/**
 * Branding properties for images associated with the channel.
 */
@ApiModel(description = "Branding properties for images associated with the channel.")
@javax.annotation.Generated(value = "com.us.idl.javaidl.JavaIDLCodegen", date = "2021-08-24T20:55:04.712703200+02:00[Europe/Paris]")
public class ImageSettings {
  public static final String SERIALIZED_NAME_BACKGROUND_IMAGE_URL = "backgroundImageUrl";
  @SerializedName(SERIALIZED_NAME_BACKGROUND_IMAGE_URL)
  private LocalizedProperty backgroundImageUrl;

  public static final String SERIALIZED_NAME_BANNER_EXTERNAL_URL = "bannerExternalUrl";
  @SerializedName(SERIALIZED_NAME_BANNER_EXTERNAL_URL)
  private String bannerExternalUrl;

  public static final String SERIALIZED_NAME_BANNER_IMAGE_URL = "bannerImageUrl";
  @SerializedName(SERIALIZED_NAME_BANNER_IMAGE_URL)
  private String bannerImageUrl;

  public static final String SERIALIZED_NAME_BANNER_MOBILE_EXTRA_HD_IMAGE_URL = "bannerMobileExtraHdImageUrl";
  @SerializedName(SERIALIZED_NAME_BANNER_MOBILE_EXTRA_HD_IMAGE_URL)
  private String bannerMobileExtraHdImageUrl;

  public static final String SERIALIZED_NAME_BANNER_MOBILE_HD_IMAGE_URL = "bannerMobileHdImageUrl";
  @SerializedName(SERIALIZED_NAME_BANNER_MOBILE_HD_IMAGE_URL)
  private String bannerMobileHdImageUrl;

  public static final String SERIALIZED_NAME_BANNER_MOBILE_IMAGE_URL = "bannerMobileImageUrl";
  @SerializedName(SERIALIZED_NAME_BANNER_MOBILE_IMAGE_URL)
  private String bannerMobileImageUrl;

  public static final String SERIALIZED_NAME_BANNER_MOBILE_LOW_IMAGE_URL = "bannerMobileLowImageUrl";
  @SerializedName(SERIALIZED_NAME_BANNER_MOBILE_LOW_IMAGE_URL)
  private String bannerMobileLowImageUrl;

  public static final String SERIALIZED_NAME_BANNER_MOBILE_MEDIUM_HD_IMAGE_URL = "bannerMobileMediumHdImageUrl";
  @SerializedName(SERIALIZED_NAME_BANNER_MOBILE_MEDIUM_HD_IMAGE_URL)
  private String bannerMobileMediumHdImageUrl;

  public static final String SERIALIZED_NAME_BANNER_TABLET_EXTRA_HD_IMAGE_URL = "bannerTabletExtraHdImageUrl";
  @SerializedName(SERIALIZED_NAME_BANNER_TABLET_EXTRA_HD_IMAGE_URL)
  private String bannerTabletExtraHdImageUrl;

  public static final String SERIALIZED_NAME_BANNER_TABLET_HD_IMAGE_URL = "bannerTabletHdImageUrl";
  @SerializedName(SERIALIZED_NAME_BANNER_TABLET_HD_IMAGE_URL)
  private String bannerTabletHdImageUrl;

  public static final String SERIALIZED_NAME_BANNER_TABLET_IMAGE_URL = "bannerTabletImageUrl";
  @SerializedName(SERIALIZED_NAME_BANNER_TABLET_IMAGE_URL)
  private String bannerTabletImageUrl;

  public static final String SERIALIZED_NAME_BANNER_TABLET_LOW_IMAGE_URL = "bannerTabletLowImageUrl";
  @SerializedName(SERIALIZED_NAME_BANNER_TABLET_LOW_IMAGE_URL)
  private String bannerTabletLowImageUrl;

  public static final String SERIALIZED_NAME_BANNER_TV_HIGH_IMAGE_URL = "bannerTvHighImageUrl";
  @SerializedName(SERIALIZED_NAME_BANNER_TV_HIGH_IMAGE_URL)
  private String bannerTvHighImageUrl;

  public static final String SERIALIZED_NAME_BANNER_TV_IMAGE_URL = "bannerTvImageUrl";
  @SerializedName(SERIALIZED_NAME_BANNER_TV_IMAGE_URL)
  private String bannerTvImageUrl;

  public static final String SERIALIZED_NAME_BANNER_TV_LOW_IMAGE_URL = "bannerTvLowImageUrl";
  @SerializedName(SERIALIZED_NAME_BANNER_TV_LOW_IMAGE_URL)
  private String bannerTvLowImageUrl;

  public static final String SERIALIZED_NAME_BANNER_TV_MEDIUM_IMAGE_URL = "bannerTvMediumImageUrl";
  @SerializedName(SERIALIZED_NAME_BANNER_TV_MEDIUM_IMAGE_URL)
  private String bannerTvMediumImageUrl;

  public static final String SERIALIZED_NAME_LARGE_BRANDED_BANNER_IMAGE_IMAP_SCRIPT = "largeBrandedBannerImageImapScript";
  @SerializedName(SERIALIZED_NAME_LARGE_BRANDED_BANNER_IMAGE_IMAP_SCRIPT)
  private LocalizedProperty largeBrandedBannerImageImapScript;

  public static final String SERIALIZED_NAME_LARGE_BRANDED_BANNER_IMAGE_URL = "largeBrandedBannerImageUrl";
  @SerializedName(SERIALIZED_NAME_LARGE_BRANDED_BANNER_IMAGE_URL)
  private LocalizedProperty largeBrandedBannerImageUrl;

  public static final String SERIALIZED_NAME_SMALL_BRANDED_BANNER_IMAGE_IMAP_SCRIPT = "smallBrandedBannerImageImapScript";
  @SerializedName(SERIALIZED_NAME_SMALL_BRANDED_BANNER_IMAGE_IMAP_SCRIPT)
  private LocalizedProperty smallBrandedBannerImageImapScript;

  public static final String SERIALIZED_NAME_SMALL_BRANDED_BANNER_IMAGE_URL = "smallBrandedBannerImageUrl";
  @SerializedName(SERIALIZED_NAME_SMALL_BRANDED_BANNER_IMAGE_URL)
  private LocalizedProperty smallBrandedBannerImageUrl;

  public static final String SERIALIZED_NAME_TRACKING_IMAGE_URL = "trackingImageUrl";
  @SerializedName(SERIALIZED_NAME_TRACKING_IMAGE_URL)
  private String trackingImageUrl;

  public static final String SERIALIZED_NAME_WATCH_ICON_IMAGE_URL = "watchIconImageUrl";
  @SerializedName(SERIALIZED_NAME_WATCH_ICON_IMAGE_URL)
  private String watchIconImageUrl;


  public ImageSettings backgroundImageUrl(LocalizedProperty backgroundImageUrl) {
    
    this.backgroundImageUrl = backgroundImageUrl;
    return this;
  }

   /**
   * Get backgroundImageUrl
   * @return backgroundImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalizedProperty getBackgroundImageUrl() {
    return backgroundImageUrl;
  }


  public void setBackgroundImageUrl(LocalizedProperty backgroundImageUrl) {
    this.backgroundImageUrl = backgroundImageUrl;
  }


  public ImageSettings bannerExternalUrl(String bannerExternalUrl) {
    
    this.bannerExternalUrl = bannerExternalUrl;
    return this;
  }

   /**
   * This is generated when a ChannelBanner.Insert request has succeeded for the given channel.
   * @return bannerExternalUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "This is generated when a ChannelBanner.Insert request has succeeded for the given channel.")

  public String getBannerExternalUrl() {
    return bannerExternalUrl;
  }


  public void setBannerExternalUrl(String bannerExternalUrl) {
    this.bannerExternalUrl = bannerExternalUrl;
  }


  public ImageSettings bannerImageUrl(String bannerImageUrl) {
    
    this.bannerImageUrl = bannerImageUrl;
    return this;
  }

   /**
   * Banner image. Desktop size (1060x175).
   * @return bannerImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Banner image. Desktop size (1060x175).")

  public String getBannerImageUrl() {
    return bannerImageUrl;
  }


  public void setBannerImageUrl(String bannerImageUrl) {
    this.bannerImageUrl = bannerImageUrl;
  }


  public ImageSettings bannerMobileExtraHdImageUrl(String bannerMobileExtraHdImageUrl) {
    
    this.bannerMobileExtraHdImageUrl = bannerMobileExtraHdImageUrl;
    return this;
  }

   /**
   * Banner image. Mobile size high resolution (1440x395).
   * @return bannerMobileExtraHdImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Banner image. Mobile size high resolution (1440x395).")

  public String getBannerMobileExtraHdImageUrl() {
    return bannerMobileExtraHdImageUrl;
  }


  public void setBannerMobileExtraHdImageUrl(String bannerMobileExtraHdImageUrl) {
    this.bannerMobileExtraHdImageUrl = bannerMobileExtraHdImageUrl;
  }


  public ImageSettings bannerMobileHdImageUrl(String bannerMobileHdImageUrl) {
    
    this.bannerMobileHdImageUrl = bannerMobileHdImageUrl;
    return this;
  }

   /**
   * Banner image. Mobile size high resolution (1280x360).
   * @return bannerMobileHdImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Banner image. Mobile size high resolution (1280x360).")

  public String getBannerMobileHdImageUrl() {
    return bannerMobileHdImageUrl;
  }


  public void setBannerMobileHdImageUrl(String bannerMobileHdImageUrl) {
    this.bannerMobileHdImageUrl = bannerMobileHdImageUrl;
  }


  public ImageSettings bannerMobileImageUrl(String bannerMobileImageUrl) {
    
    this.bannerMobileImageUrl = bannerMobileImageUrl;
    return this;
  }

   /**
   * Banner image. Mobile size (640x175).
   * @return bannerMobileImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Banner image. Mobile size (640x175).")

  public String getBannerMobileImageUrl() {
    return bannerMobileImageUrl;
  }


  public void setBannerMobileImageUrl(String bannerMobileImageUrl) {
    this.bannerMobileImageUrl = bannerMobileImageUrl;
  }


  public ImageSettings bannerMobileLowImageUrl(String bannerMobileLowImageUrl) {
    
    this.bannerMobileLowImageUrl = bannerMobileLowImageUrl;
    return this;
  }

   /**
   * Banner image. Mobile size low resolution (320x88).
   * @return bannerMobileLowImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Banner image. Mobile size low resolution (320x88).")

  public String getBannerMobileLowImageUrl() {
    return bannerMobileLowImageUrl;
  }


  public void setBannerMobileLowImageUrl(String bannerMobileLowImageUrl) {
    this.bannerMobileLowImageUrl = bannerMobileLowImageUrl;
  }


  public ImageSettings bannerMobileMediumHdImageUrl(String bannerMobileMediumHdImageUrl) {
    
    this.bannerMobileMediumHdImageUrl = bannerMobileMediumHdImageUrl;
    return this;
  }

   /**
   * Banner image. Mobile size medium/high resolution (960x263).
   * @return bannerMobileMediumHdImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Banner image. Mobile size medium/high resolution (960x263).")

  public String getBannerMobileMediumHdImageUrl() {
    return bannerMobileMediumHdImageUrl;
  }


  public void setBannerMobileMediumHdImageUrl(String bannerMobileMediumHdImageUrl) {
    this.bannerMobileMediumHdImageUrl = bannerMobileMediumHdImageUrl;
  }


  public ImageSettings bannerTabletExtraHdImageUrl(String bannerTabletExtraHdImageUrl) {
    
    this.bannerTabletExtraHdImageUrl = bannerTabletExtraHdImageUrl;
    return this;
  }

   /**
   * Banner image. Tablet size extra high resolution (2560x424).
   * @return bannerTabletExtraHdImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Banner image. Tablet size extra high resolution (2560x424).")

  public String getBannerTabletExtraHdImageUrl() {
    return bannerTabletExtraHdImageUrl;
  }


  public void setBannerTabletExtraHdImageUrl(String bannerTabletExtraHdImageUrl) {
    this.bannerTabletExtraHdImageUrl = bannerTabletExtraHdImageUrl;
  }


  public ImageSettings bannerTabletHdImageUrl(String bannerTabletHdImageUrl) {
    
    this.bannerTabletHdImageUrl = bannerTabletHdImageUrl;
    return this;
  }

   /**
   * Banner image. Tablet size high resolution (2276x377).
   * @return bannerTabletHdImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Banner image. Tablet size high resolution (2276x377).")

  public String getBannerTabletHdImageUrl() {
    return bannerTabletHdImageUrl;
  }


  public void setBannerTabletHdImageUrl(String bannerTabletHdImageUrl) {
    this.bannerTabletHdImageUrl = bannerTabletHdImageUrl;
  }


  public ImageSettings bannerTabletImageUrl(String bannerTabletImageUrl) {
    
    this.bannerTabletImageUrl = bannerTabletImageUrl;
    return this;
  }

   /**
   * Banner image. Tablet size (1707x283).
   * @return bannerTabletImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Banner image. Tablet size (1707x283).")

  public String getBannerTabletImageUrl() {
    return bannerTabletImageUrl;
  }


  public void setBannerTabletImageUrl(String bannerTabletImageUrl) {
    this.bannerTabletImageUrl = bannerTabletImageUrl;
  }


  public ImageSettings bannerTabletLowImageUrl(String bannerTabletLowImageUrl) {
    
    this.bannerTabletLowImageUrl = bannerTabletLowImageUrl;
    return this;
  }

   /**
   * Banner image. Tablet size low resolution (1138x188).
   * @return bannerTabletLowImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Banner image. Tablet size low resolution (1138x188).")

  public String getBannerTabletLowImageUrl() {
    return bannerTabletLowImageUrl;
  }


  public void setBannerTabletLowImageUrl(String bannerTabletLowImageUrl) {
    this.bannerTabletLowImageUrl = bannerTabletLowImageUrl;
  }


  public ImageSettings bannerTvHighImageUrl(String bannerTvHighImageUrl) {
    
    this.bannerTvHighImageUrl = bannerTvHighImageUrl;
    return this;
  }

   /**
   * Banner image. TV size high resolution (1920x1080).
   * @return bannerTvHighImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Banner image. TV size high resolution (1920x1080).")

  public String getBannerTvHighImageUrl() {
    return bannerTvHighImageUrl;
  }


  public void setBannerTvHighImageUrl(String bannerTvHighImageUrl) {
    this.bannerTvHighImageUrl = bannerTvHighImageUrl;
  }


  public ImageSettings bannerTvImageUrl(String bannerTvImageUrl) {
    
    this.bannerTvImageUrl = bannerTvImageUrl;
    return this;
  }

   /**
   * Banner image. TV size extra high resolution (2120x1192).
   * @return bannerTvImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Banner image. TV size extra high resolution (2120x1192).")

  public String getBannerTvImageUrl() {
    return bannerTvImageUrl;
  }


  public void setBannerTvImageUrl(String bannerTvImageUrl) {
    this.bannerTvImageUrl = bannerTvImageUrl;
  }


  public ImageSettings bannerTvLowImageUrl(String bannerTvLowImageUrl) {
    
    this.bannerTvLowImageUrl = bannerTvLowImageUrl;
    return this;
  }

   /**
   * Banner image. TV size low resolution (854x480).
   * @return bannerTvLowImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Banner image. TV size low resolution (854x480).")

  public String getBannerTvLowImageUrl() {
    return bannerTvLowImageUrl;
  }


  public void setBannerTvLowImageUrl(String bannerTvLowImageUrl) {
    this.bannerTvLowImageUrl = bannerTvLowImageUrl;
  }


  public ImageSettings bannerTvMediumImageUrl(String bannerTvMediumImageUrl) {
    
    this.bannerTvMediumImageUrl = bannerTvMediumImageUrl;
    return this;
  }

   /**
   * Banner image. TV size medium resolution (1280x720).
   * @return bannerTvMediumImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Banner image. TV size medium resolution (1280x720).")

  public String getBannerTvMediumImageUrl() {
    return bannerTvMediumImageUrl;
  }


  public void setBannerTvMediumImageUrl(String bannerTvMediumImageUrl) {
    this.bannerTvMediumImageUrl = bannerTvMediumImageUrl;
  }


  public ImageSettings largeBrandedBannerImageImapScript(LocalizedProperty largeBrandedBannerImageImapScript) {
    
    this.largeBrandedBannerImageImapScript = largeBrandedBannerImageImapScript;
    return this;
  }

   /**
   * Get largeBrandedBannerImageImapScript
   * @return largeBrandedBannerImageImapScript
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalizedProperty getLargeBrandedBannerImageImapScript() {
    return largeBrandedBannerImageImapScript;
  }


  public void setLargeBrandedBannerImageImapScript(LocalizedProperty largeBrandedBannerImageImapScript) {
    this.largeBrandedBannerImageImapScript = largeBrandedBannerImageImapScript;
  }


  public ImageSettings largeBrandedBannerImageUrl(LocalizedProperty largeBrandedBannerImageUrl) {
    
    this.largeBrandedBannerImageUrl = largeBrandedBannerImageUrl;
    return this;
  }

   /**
   * Get largeBrandedBannerImageUrl
   * @return largeBrandedBannerImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalizedProperty getLargeBrandedBannerImageUrl() {
    return largeBrandedBannerImageUrl;
  }


  public void setLargeBrandedBannerImageUrl(LocalizedProperty largeBrandedBannerImageUrl) {
    this.largeBrandedBannerImageUrl = largeBrandedBannerImageUrl;
  }


  public ImageSettings smallBrandedBannerImageImapScript(LocalizedProperty smallBrandedBannerImageImapScript) {
    
    this.smallBrandedBannerImageImapScript = smallBrandedBannerImageImapScript;
    return this;
  }

   /**
   * Get smallBrandedBannerImageImapScript
   * @return smallBrandedBannerImageImapScript
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalizedProperty getSmallBrandedBannerImageImapScript() {
    return smallBrandedBannerImageImapScript;
  }


  public void setSmallBrandedBannerImageImapScript(LocalizedProperty smallBrandedBannerImageImapScript) {
    this.smallBrandedBannerImageImapScript = smallBrandedBannerImageImapScript;
  }


  public ImageSettings smallBrandedBannerImageUrl(LocalizedProperty smallBrandedBannerImageUrl) {
    
    this.smallBrandedBannerImageUrl = smallBrandedBannerImageUrl;
    return this;
  }

   /**
   * Get smallBrandedBannerImageUrl
   * @return smallBrandedBannerImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalizedProperty getSmallBrandedBannerImageUrl() {
    return smallBrandedBannerImageUrl;
  }


  public void setSmallBrandedBannerImageUrl(LocalizedProperty smallBrandedBannerImageUrl) {
    this.smallBrandedBannerImageUrl = smallBrandedBannerImageUrl;
  }


  public ImageSettings trackingImageUrl(String trackingImageUrl) {
    
    this.trackingImageUrl = trackingImageUrl;
    return this;
  }

   /**
   * The URL for a 1px by 1px tracking pixel that can be used to collect statistics for views of the channel or video pages.
   * @return trackingImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The URL for a 1px by 1px tracking pixel that can be used to collect statistics for views of the channel or video pages.")

  public String getTrackingImageUrl() {
    return trackingImageUrl;
  }


  public void setTrackingImageUrl(String trackingImageUrl) {
    this.trackingImageUrl = trackingImageUrl;
  }


  public ImageSettings watchIconImageUrl(String watchIconImageUrl) {
    
    this.watchIconImageUrl = watchIconImageUrl;
    return this;
  }

   /**
   * Get watchIconImageUrl
   * @return watchIconImageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getWatchIconImageUrl() {
    return watchIconImageUrl;
  }


  public void setWatchIconImageUrl(String watchIconImageUrl) {
    this.watchIconImageUrl = watchIconImageUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageSettings imageSettings = (ImageSettings) o;
    return Objects.equals(this.backgroundImageUrl, imageSettings.backgroundImageUrl) &&
        Objects.equals(this.bannerExternalUrl, imageSettings.bannerExternalUrl) &&
        Objects.equals(this.bannerImageUrl, imageSettings.bannerImageUrl) &&
        Objects.equals(this.bannerMobileExtraHdImageUrl, imageSettings.bannerMobileExtraHdImageUrl) &&
        Objects.equals(this.bannerMobileHdImageUrl, imageSettings.bannerMobileHdImageUrl) &&
        Objects.equals(this.bannerMobileImageUrl, imageSettings.bannerMobileImageUrl) &&
        Objects.equals(this.bannerMobileLowImageUrl, imageSettings.bannerMobileLowImageUrl) &&
        Objects.equals(this.bannerMobileMediumHdImageUrl, imageSettings.bannerMobileMediumHdImageUrl) &&
        Objects.equals(this.bannerTabletExtraHdImageUrl, imageSettings.bannerTabletExtraHdImageUrl) &&
        Objects.equals(this.bannerTabletHdImageUrl, imageSettings.bannerTabletHdImageUrl) &&
        Objects.equals(this.bannerTabletImageUrl, imageSettings.bannerTabletImageUrl) &&
        Objects.equals(this.bannerTabletLowImageUrl, imageSettings.bannerTabletLowImageUrl) &&
        Objects.equals(this.bannerTvHighImageUrl, imageSettings.bannerTvHighImageUrl) &&
        Objects.equals(this.bannerTvImageUrl, imageSettings.bannerTvImageUrl) &&
        Objects.equals(this.bannerTvLowImageUrl, imageSettings.bannerTvLowImageUrl) &&
        Objects.equals(this.bannerTvMediumImageUrl, imageSettings.bannerTvMediumImageUrl) &&
        Objects.equals(this.largeBrandedBannerImageImapScript, imageSettings.largeBrandedBannerImageImapScript) &&
        Objects.equals(this.largeBrandedBannerImageUrl, imageSettings.largeBrandedBannerImageUrl) &&
        Objects.equals(this.smallBrandedBannerImageImapScript, imageSettings.smallBrandedBannerImageImapScript) &&
        Objects.equals(this.smallBrandedBannerImageUrl, imageSettings.smallBrandedBannerImageUrl) &&
        Objects.equals(this.trackingImageUrl, imageSettings.trackingImageUrl) &&
        Objects.equals(this.watchIconImageUrl, imageSettings.watchIconImageUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backgroundImageUrl, bannerExternalUrl, bannerImageUrl, bannerMobileExtraHdImageUrl, bannerMobileHdImageUrl, bannerMobileImageUrl, bannerMobileLowImageUrl, bannerMobileMediumHdImageUrl, bannerTabletExtraHdImageUrl, bannerTabletHdImageUrl, bannerTabletImageUrl, bannerTabletLowImageUrl, bannerTvHighImageUrl, bannerTvImageUrl, bannerTvLowImageUrl, bannerTvMediumImageUrl, largeBrandedBannerImageImapScript, largeBrandedBannerImageUrl, smallBrandedBannerImageImapScript, smallBrandedBannerImageUrl, trackingImageUrl, watchIconImageUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageSettings {\n");
    sb.append("    backgroundImageUrl: ").append(toIndentedString(backgroundImageUrl)).append("\n");
    sb.append("    bannerExternalUrl: ").append(toIndentedString(bannerExternalUrl)).append("\n");
    sb.append("    bannerImageUrl: ").append(toIndentedString(bannerImageUrl)).append("\n");
    sb.append("    bannerMobileExtraHdImageUrl: ").append(toIndentedString(bannerMobileExtraHdImageUrl)).append("\n");
    sb.append("    bannerMobileHdImageUrl: ").append(toIndentedString(bannerMobileHdImageUrl)).append("\n");
    sb.append("    bannerMobileImageUrl: ").append(toIndentedString(bannerMobileImageUrl)).append("\n");
    sb.append("    bannerMobileLowImageUrl: ").append(toIndentedString(bannerMobileLowImageUrl)).append("\n");
    sb.append("    bannerMobileMediumHdImageUrl: ").append(toIndentedString(bannerMobileMediumHdImageUrl)).append("\n");
    sb.append("    bannerTabletExtraHdImageUrl: ").append(toIndentedString(bannerTabletExtraHdImageUrl)).append("\n");
    sb.append("    bannerTabletHdImageUrl: ").append(toIndentedString(bannerTabletHdImageUrl)).append("\n");
    sb.append("    bannerTabletImageUrl: ").append(toIndentedString(bannerTabletImageUrl)).append("\n");
    sb.append("    bannerTabletLowImageUrl: ").append(toIndentedString(bannerTabletLowImageUrl)).append("\n");
    sb.append("    bannerTvHighImageUrl: ").append(toIndentedString(bannerTvHighImageUrl)).append("\n");
    sb.append("    bannerTvImageUrl: ").append(toIndentedString(bannerTvImageUrl)).append("\n");
    sb.append("    bannerTvLowImageUrl: ").append(toIndentedString(bannerTvLowImageUrl)).append("\n");
    sb.append("    bannerTvMediumImageUrl: ").append(toIndentedString(bannerTvMediumImageUrl)).append("\n");
    sb.append("    largeBrandedBannerImageImapScript: ").append(toIndentedString(largeBrandedBannerImageImapScript)).append("\n");
    sb.append("    largeBrandedBannerImageUrl: ").append(toIndentedString(largeBrandedBannerImageUrl)).append("\n");
    sb.append("    smallBrandedBannerImageImapScript: ").append(toIndentedString(smallBrandedBannerImageImapScript)).append("\n");
    sb.append("    smallBrandedBannerImageUrl: ").append(toIndentedString(smallBrandedBannerImageUrl)).append("\n");
    sb.append("    trackingImageUrl: ").append(toIndentedString(trackingImageUrl)).append("\n");
    sb.append("    watchIconImageUrl: ").append(toIndentedString(watchIconImageUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

