/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.LiveBroadcastContentDetails;
import org.openapitools.client.model.LiveBroadcastSnippet;
import org.openapitools.client.model.LiveBroadcastStatistics;
import org.openapitools.client.model.LiveBroadcastStatus;

/**
 * A *liveBroadcast* resource represents an event that will be streamed, via live video, on YouTube.
 */
@ApiModel(description = "A *liveBroadcast* resource represents an event that will be streamed, via live video, on YouTube.")
@javax.annotation.Generated(value = "com.us.idl.javaidl.JavaIDLCodegen", date = "2021-08-24T20:55:04.712703200+02:00[Europe/Paris]")
public class LiveBroadcast {
  public static final String SERIALIZED_NAME_CONTENT_DETAILS = "contentDetails";
  @SerializedName(SERIALIZED_NAME_CONTENT_DETAILS)
  private LiveBroadcastContentDetails contentDetails;

  public static final String SERIALIZED_NAME_ETAG = "etag";
  @SerializedName(SERIALIZED_NAME_ETAG)
  private String etag;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  private String kind = "youtube#liveBroadcast";

  public static final String SERIALIZED_NAME_SNIPPET = "snippet";
  @SerializedName(SERIALIZED_NAME_SNIPPET)
  private LiveBroadcastSnippet snippet;

  public static final String SERIALIZED_NAME_STATISTICS = "statistics";
  @SerializedName(SERIALIZED_NAME_STATISTICS)
  private LiveBroadcastStatistics statistics;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private LiveBroadcastStatus status;


  public LiveBroadcast contentDetails(LiveBroadcastContentDetails contentDetails) {
    
    this.contentDetails = contentDetails;
    return this;
  }

   /**
   * Get contentDetails
   * @return contentDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LiveBroadcastContentDetails getContentDetails() {
    return contentDetails;
  }


  public void setContentDetails(LiveBroadcastContentDetails contentDetails) {
    this.contentDetails = contentDetails;
  }


  public LiveBroadcast etag(String etag) {
    
    this.etag = etag;
    return this;
  }

   /**
   * Etag of this resource.
   * @return etag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Etag of this resource.")

  public String getEtag() {
    return etag;
  }


  public void setEtag(String etag) {
    this.etag = etag;
  }


  public LiveBroadcast id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The ID that YouTube assigns to uniquely identify the broadcast.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID that YouTube assigns to uniquely identify the broadcast.")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public LiveBroadcast kind(String kind) {
    
    this.kind = kind;
    return this;
  }

   /**
   * Identifies what kind of resource this is. Value: the fixed string \&quot;youtube#liveBroadcast\&quot;.
   * @return kind
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Identifies what kind of resource this is. Value: the fixed string \"youtube#liveBroadcast\".")

  public String getKind() {
    return kind;
  }


  public void setKind(String kind) {
    this.kind = kind;
  }


  public LiveBroadcast snippet(LiveBroadcastSnippet snippet) {
    
    this.snippet = snippet;
    return this;
  }

   /**
   * Get snippet
   * @return snippet
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LiveBroadcastSnippet getSnippet() {
    return snippet;
  }


  public void setSnippet(LiveBroadcastSnippet snippet) {
    this.snippet = snippet;
  }


  public LiveBroadcast statistics(LiveBroadcastStatistics statistics) {
    
    this.statistics = statistics;
    return this;
  }

   /**
   * Get statistics
   * @return statistics
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LiveBroadcastStatistics getStatistics() {
    return statistics;
  }


  public void setStatistics(LiveBroadcastStatistics statistics) {
    this.statistics = statistics;
  }


  public LiveBroadcast status(LiveBroadcastStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LiveBroadcastStatus getStatus() {
    return status;
  }


  public void setStatus(LiveBroadcastStatus status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LiveBroadcast liveBroadcast = (LiveBroadcast) o;
    return Objects.equals(this.contentDetails, liveBroadcast.contentDetails) &&
        Objects.equals(this.etag, liveBroadcast.etag) &&
        Objects.equals(this.id, liveBroadcast.id) &&
        Objects.equals(this.kind, liveBroadcast.kind) &&
        Objects.equals(this.snippet, liveBroadcast.snippet) &&
        Objects.equals(this.statistics, liveBroadcast.statistics) &&
        Objects.equals(this.status, liveBroadcast.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contentDetails, etag, id, kind, snippet, statistics, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LiveBroadcast {\n");
    sb.append("    contentDetails: ").append(toIndentedString(contentDetails)).append("\n");
    sb.append("    etag: ").append(toIndentedString(etag)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    snippet: ").append(toIndentedString(snippet)).append("\n");
    sb.append("    statistics: ").append(toIndentedString(statistics)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

