/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * LiveStreamSnippet
 */
@javax.annotation.Generated(value = "com.us.idl.javaidl.JavaIDLCodegen", date = "2021-08-24T20:55:04.712703200+02:00[Europe/Paris]")
public class LiveStreamSnippet {
  public static final String SERIALIZED_NAME_CHANNEL_ID = "channelId";
  @SerializedName(SERIALIZED_NAME_CHANNEL_ID)
  private String channelId;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_IS_DEFAULT_STREAM = "isDefaultStream";
  @SerializedName(SERIALIZED_NAME_IS_DEFAULT_STREAM)
  private Boolean isDefaultStream;

  public static final String SERIALIZED_NAME_PUBLISHED_AT = "publishedAt";
  @SerializedName(SERIALIZED_NAME_PUBLISHED_AT)
  private OffsetDateTime publishedAt;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;


  public LiveStreamSnippet channelId(String channelId) {
    
    this.channelId = channelId;
    return this;
  }

   /**
   * The ID that YouTube uses to uniquely identify the channel that is transmitting the stream.
   * @return channelId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID that YouTube uses to uniquely identify the channel that is transmitting the stream.")

  public String getChannelId() {
    return channelId;
  }


  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }


  public LiveStreamSnippet description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * The stream&#39;s description. The value cannot be longer than 10000 characters.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The stream's description. The value cannot be longer than 10000 characters.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public LiveStreamSnippet isDefaultStream(Boolean isDefaultStream) {
    
    this.isDefaultStream = isDefaultStream;
    return this;
  }

   /**
   * Get isDefaultStream
   * @return isDefaultStream
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsDefaultStream() {
    return isDefaultStream;
  }


  public void setIsDefaultStream(Boolean isDefaultStream) {
    this.isDefaultStream = isDefaultStream;
  }


  public LiveStreamSnippet publishedAt(OffsetDateTime publishedAt) {
    
    this.publishedAt = publishedAt;
    return this;
  }

   /**
   * The date and time that the stream was created.
   * @return publishedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time that the stream was created.")

  public OffsetDateTime getPublishedAt() {
    return publishedAt;
  }


  public void setPublishedAt(OffsetDateTime publishedAt) {
    this.publishedAt = publishedAt;
  }


  public LiveStreamSnippet title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * The stream&#39;s title. The value must be between 1 and 128 characters long.
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The stream's title. The value must be between 1 and 128 characters long.")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LiveStreamSnippet liveStreamSnippet = (LiveStreamSnippet) o;
    return Objects.equals(this.channelId, liveStreamSnippet.channelId) &&
        Objects.equals(this.description, liveStreamSnippet.description) &&
        Objects.equals(this.isDefaultStream, liveStreamSnippet.isDefaultStream) &&
        Objects.equals(this.publishedAt, liveStreamSnippet.publishedAt) &&
        Objects.equals(this.title, liveStreamSnippet.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelId, description, isDefaultStream, publishedAt, title);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LiveStreamSnippet {\n");
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    isDefaultStream: ").append(toIndentedString(isDefaultStream)).append("\n");
    sb.append("    publishedAt: ").append(toIndentedString(publishedAt)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

