/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Detailed settings of a stream.
 */
@ApiModel(description = "Detailed settings of a stream.")
@javax.annotation.Generated(value = "com.us.idl.javaidl.JavaIDLCodegen", date = "2021-08-24T20:55:04.712703200+02:00[Europe/Paris]")
public class LiveStreamContentDetails {
  public static final String SERIALIZED_NAME_CLOSED_CAPTIONS_INGESTION_URL = "closedCaptionsIngestionUrl";
  @SerializedName(SERIALIZED_NAME_CLOSED_CAPTIONS_INGESTION_URL)
  private String closedCaptionsIngestionUrl;

  public static final String SERIALIZED_NAME_IS_REUSABLE = "isReusable";
  @SerializedName(SERIALIZED_NAME_IS_REUSABLE)
  private Boolean isReusable;


  public LiveStreamContentDetails closedCaptionsIngestionUrl(String closedCaptionsIngestionUrl) {
    
    this.closedCaptionsIngestionUrl = closedCaptionsIngestionUrl;
    return this;
  }

   /**
   * The ingestion URL where the closed captions of this stream are sent.
   * @return closedCaptionsIngestionUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ingestion URL where the closed captions of this stream are sent.")

  public String getClosedCaptionsIngestionUrl() {
    return closedCaptionsIngestionUrl;
  }


  public void setClosedCaptionsIngestionUrl(String closedCaptionsIngestionUrl) {
    this.closedCaptionsIngestionUrl = closedCaptionsIngestionUrl;
  }


  public LiveStreamContentDetails isReusable(Boolean isReusable) {
    
    this.isReusable = isReusable;
    return this;
  }

   /**
   * Indicates whether the stream is reusable, which means that it can be bound to multiple broadcasts. It is common for broadcasters to reuse the same stream for many different broadcasts if those broadcasts occur at different times. If you set this value to false, then the stream will not be reusable, which means that it can only be bound to one broadcast. Non-reusable streams differ from reusable streams in the following ways: - A non-reusable stream can only be bound to one broadcast. - A non-reusable stream might be deleted by an automated process after the broadcast ends. - The liveStreams.list method does not list non-reusable streams if you call the method and set the mine parameter to true. The only way to use that method to retrieve the resource for a non-reusable stream is to use the id parameter to identify the stream. 
   * @return isReusable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates whether the stream is reusable, which means that it can be bound to multiple broadcasts. It is common for broadcasters to reuse the same stream for many different broadcasts if those broadcasts occur at different times. If you set this value to false, then the stream will not be reusable, which means that it can only be bound to one broadcast. Non-reusable streams differ from reusable streams in the following ways: - A non-reusable stream can only be bound to one broadcast. - A non-reusable stream might be deleted by an automated process after the broadcast ends. - The liveStreams.list method does not list non-reusable streams if you call the method and set the mine parameter to true. The only way to use that method to retrieve the resource for a non-reusable stream is to use the id parameter to identify the stream. ")

  public Boolean getIsReusable() {
    return isReusable;
  }


  public void setIsReusable(Boolean isReusable) {
    this.isReusable = isReusable;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LiveStreamContentDetails liveStreamContentDetails = (LiveStreamContentDetails) o;
    return Objects.equals(this.closedCaptionsIngestionUrl, liveStreamContentDetails.closedCaptionsIngestionUrl) &&
        Objects.equals(this.isReusable, liveStreamContentDetails.isReusable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(closedCaptionsIngestionUrl, isReusable);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LiveStreamContentDetails {\n");
    sb.append("    closedCaptionsIngestionUrl: ").append(toIndentedString(closedCaptionsIngestionUrl)).append("\n");
    sb.append("    isReusable: ").append(toIndentedString(isReusable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

