/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.LiveStreamHealthStatus;

/**
 * Brief description of the live stream status.
 */
@ApiModel(description = "Brief description of the live stream status.")
@javax.annotation.Generated(value = "com.us.idl.javaidl.JavaIDLCodegen", date = "2021-08-24T20:55:04.712703200+02:00[Europe/Paris]")
public class LiveStreamStatus {
  public static final String SERIALIZED_NAME_HEALTH_STATUS = "healthStatus";
  @SerializedName(SERIALIZED_NAME_HEALTH_STATUS)
  private LiveStreamHealthStatus healthStatus;

  /**
   * Gets or Sets streamStatus
   */
  @JsonAdapter(StreamStatusEnum.Adapter.class)
  public enum StreamStatusEnum {
    CREATED("created"),
    
    READY("ready"),
    
    ACTIVE("active"),
    
    INACTIVE("inactive"),
    
    ERROR("error");

    private String value;

    StreamStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StreamStatusEnum fromValue(String value) {
      for (StreamStatusEnum b : StreamStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StreamStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StreamStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StreamStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StreamStatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STREAM_STATUS = "streamStatus";
  @SerializedName(SERIALIZED_NAME_STREAM_STATUS)
  private StreamStatusEnum streamStatus;


  public LiveStreamStatus healthStatus(LiveStreamHealthStatus healthStatus) {
    
    this.healthStatus = healthStatus;
    return this;
  }

   /**
   * Get healthStatus
   * @return healthStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LiveStreamHealthStatus getHealthStatus() {
    return healthStatus;
  }


  public void setHealthStatus(LiveStreamHealthStatus healthStatus) {
    this.healthStatus = healthStatus;
  }


  public LiveStreamStatus streamStatus(StreamStatusEnum streamStatus) {
    
    this.streamStatus = streamStatus;
    return this;
  }

   /**
   * Get streamStatus
   * @return streamStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public StreamStatusEnum getStreamStatus() {
    return streamStatus;
  }


  public void setStreamStatus(StreamStatusEnum streamStatus) {
    this.streamStatus = streamStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LiveStreamStatus liveStreamStatus = (LiveStreamStatus) o;
    return Objects.equals(this.healthStatus, liveStreamStatus.healthStatus) &&
        Objects.equals(this.streamStatus, liveStreamStatus.streamStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(healthStatus, streamStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LiveStreamStatus {\n");
    sb.append("    healthStatus: ").append(toIndentedString(healthStatus)).append("\n");
    sb.append("    streamStatus: ").append(toIndentedString(streamStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

