/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.LiveChatMessageAuthorDetails;
import org.openapitools.client.model.LiveChatMessageSnippet;

/**
 * A *liveChatMessage* resource represents a chat message in a YouTube Live Chat.
 */
@ApiModel(description = "A *liveChatMessage* resource represents a chat message in a YouTube Live Chat.")
@javax.annotation.Generated(value = "com.us.idl.javaidl.JavaIDLCodegen", date = "2021-08-24T20:55:04.712703200+02:00[Europe/Paris]")
public class LiveChatMessage {
  public static final String SERIALIZED_NAME_AUTHOR_DETAILS = "authorDetails";
  @SerializedName(SERIALIZED_NAME_AUTHOR_DETAILS)
  private LiveChatMessageAuthorDetails authorDetails;

  public static final String SERIALIZED_NAME_ETAG = "etag";
  @SerializedName(SERIALIZED_NAME_ETAG)
  private String etag;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  private String kind = "youtube#liveChatMessage";

  public static final String SERIALIZED_NAME_SNIPPET = "snippet";
  @SerializedName(SERIALIZED_NAME_SNIPPET)
  private LiveChatMessageSnippet snippet;


  public LiveChatMessage authorDetails(LiveChatMessageAuthorDetails authorDetails) {
    
    this.authorDetails = authorDetails;
    return this;
  }

   /**
   * Get authorDetails
   * @return authorDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LiveChatMessageAuthorDetails getAuthorDetails() {
    return authorDetails;
  }


  public void setAuthorDetails(LiveChatMessageAuthorDetails authorDetails) {
    this.authorDetails = authorDetails;
  }


  public LiveChatMessage etag(String etag) {
    
    this.etag = etag;
    return this;
  }

   /**
   * Etag of this resource.
   * @return etag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Etag of this resource.")

  public String getEtag() {
    return etag;
  }


  public void setEtag(String etag) {
    this.etag = etag;
  }


  public LiveChatMessage id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The ID that YouTube assigns to uniquely identify the message.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID that YouTube assigns to uniquely identify the message.")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public LiveChatMessage kind(String kind) {
    
    this.kind = kind;
    return this;
  }

   /**
   * Identifies what kind of resource this is. Value: the fixed string \&quot;youtube#liveChatMessage\&quot;.
   * @return kind
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Identifies what kind of resource this is. Value: the fixed string \"youtube#liveChatMessage\".")

  public String getKind() {
    return kind;
  }


  public void setKind(String kind) {
    this.kind = kind;
  }


  public LiveChatMessage snippet(LiveChatMessageSnippet snippet) {
    
    this.snippet = snippet;
    return this;
  }

   /**
   * Get snippet
   * @return snippet
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LiveChatMessageSnippet getSnippet() {
    return snippet;
  }


  public void setSnippet(LiveChatMessageSnippet snippet) {
    this.snippet = snippet;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LiveChatMessage liveChatMessage = (LiveChatMessage) o;
    return Objects.equals(this.authorDetails, liveChatMessage.authorDetails) &&
        Objects.equals(this.etag, liveChatMessage.etag) &&
        Objects.equals(this.id, liveChatMessage.id) &&
        Objects.equals(this.kind, liveChatMessage.kind) &&
        Objects.equals(this.snippet, liveChatMessage.snippet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authorDetails, etag, id, kind, snippet);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LiveChatMessage {\n");
    sb.append("    authorDetails: ").append(toIndentedString(authorDetails)).append("\n");
    sb.append("    etag: ").append(toIndentedString(etag)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    snippet: ").append(toIndentedString(snippet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

