/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MembershipsDuration
 */
@javax.annotation.Generated(value = "com.us.idl.javaidl.JavaIDLCodegen", date = "2021-08-24T20:55:04.712703200+02:00[Europe/Paris]")
public class MembershipsDuration {
  public static final String SERIALIZED_NAME_MEMBER_SINCE = "memberSince";
  @SerializedName(SERIALIZED_NAME_MEMBER_SINCE)
  private String memberSince;

  public static final String SERIALIZED_NAME_MEMBER_TOTAL_DURATION_MONTHS = "memberTotalDurationMonths";
  @SerializedName(SERIALIZED_NAME_MEMBER_TOTAL_DURATION_MONTHS)
  private Integer memberTotalDurationMonths;


  public MembershipsDuration memberSince(String memberSince) {
    
    this.memberSince = memberSince;
    return this;
  }

   /**
   * The date and time when the user became a continuous member across all levels.
   * @return memberSince
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time when the user became a continuous member across all levels.")

  public String getMemberSince() {
    return memberSince;
  }


  public void setMemberSince(String memberSince) {
    this.memberSince = memberSince;
  }


  public MembershipsDuration memberTotalDurationMonths(Integer memberTotalDurationMonths) {
    
    this.memberTotalDurationMonths = memberTotalDurationMonths;
    return this;
  }

   /**
   * The cumulative time the user has been a member across all levels in complete months (the time is rounded down to the nearest integer).
   * @return memberTotalDurationMonths
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The cumulative time the user has been a member across all levels in complete months (the time is rounded down to the nearest integer).")

  public Integer getMemberTotalDurationMonths() {
    return memberTotalDurationMonths;
  }


  public void setMemberTotalDurationMonths(Integer memberTotalDurationMonths) {
    this.memberTotalDurationMonths = memberTotalDurationMonths;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MembershipsDuration membershipsDuration = (MembershipsDuration) o;
    return Objects.equals(this.memberSince, membershipsDuration.memberSince) &&
        Objects.equals(this.memberTotalDurationMonths, membershipsDuration.memberTotalDurationMonths);
  }

  @Override
  public int hashCode() {
    return Objects.hash(memberSince, memberTotalDurationMonths);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MembershipsDuration {\n");
    sb.append("    memberSince: ").append(toIndentedString(memberSince)).append("\n");
    sb.append("    memberTotalDurationMonths: ").append(toIndentedString(memberTotalDurationMonths)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

