/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ChannelProfileDetails;
import org.openapitools.client.model.MembershipsDetails;

/**
 * MemberSnippet
 */
@javax.annotation.Generated(value = "com.us.idl.javaidl.JavaIDLCodegen", date = "2021-08-24T20:55:04.712703200+02:00[Europe/Paris]")
public class MemberSnippet {
  public static final String SERIALIZED_NAME_CREATOR_CHANNEL_ID = "creatorChannelId";
  @SerializedName(SERIALIZED_NAME_CREATOR_CHANNEL_ID)
  private String creatorChannelId;

  public static final String SERIALIZED_NAME_MEMBER_DETAILS = "memberDetails";
  @SerializedName(SERIALIZED_NAME_MEMBER_DETAILS)
  private ChannelProfileDetails memberDetails;

  public static final String SERIALIZED_NAME_MEMBERSHIPS_DETAILS = "membershipsDetails";
  @SerializedName(SERIALIZED_NAME_MEMBERSHIPS_DETAILS)
  private MembershipsDetails membershipsDetails;


  public MemberSnippet creatorChannelId(String creatorChannelId) {
    
    this.creatorChannelId = creatorChannelId;
    return this;
  }

   /**
   * The id of the channel that&#39;s offering memberships.
   * @return creatorChannelId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The id of the channel that's offering memberships.")

  public String getCreatorChannelId() {
    return creatorChannelId;
  }


  public void setCreatorChannelId(String creatorChannelId) {
    this.creatorChannelId = creatorChannelId;
  }


  public MemberSnippet memberDetails(ChannelProfileDetails memberDetails) {
    
    this.memberDetails = memberDetails;
    return this;
  }

   /**
   * Get memberDetails
   * @return memberDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ChannelProfileDetails getMemberDetails() {
    return memberDetails;
  }


  public void setMemberDetails(ChannelProfileDetails memberDetails) {
    this.memberDetails = memberDetails;
  }


  public MemberSnippet membershipsDetails(MembershipsDetails membershipsDetails) {
    
    this.membershipsDetails = membershipsDetails;
    return this;
  }

   /**
   * Get membershipsDetails
   * @return membershipsDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MembershipsDetails getMembershipsDetails() {
    return membershipsDetails;
  }


  public void setMembershipsDetails(MembershipsDetails membershipsDetails) {
    this.membershipsDetails = membershipsDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MemberSnippet memberSnippet = (MemberSnippet) o;
    return Objects.equals(this.creatorChannelId, memberSnippet.creatorChannelId) &&
        Objects.equals(this.memberDetails, memberSnippet.memberDetails) &&
        Objects.equals(this.membershipsDetails, memberSnippet.membershipsDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creatorChannelId, memberDetails, membershipsDetails);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MemberSnippet {\n");
    sb.append("    creatorChannelId: ").append(toIndentedString(creatorChannelId)).append("\n");
    sb.append("    memberDetails: ").append(toIndentedString(memberDetails)).append("\n");
    sb.append("    membershipsDetails: ").append(toIndentedString(membershipsDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

