/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ChannelToStoreLinkDetails;

/**
 * Basic information about a third party account link, including its type and type-specific information.
 */
@ApiModel(description = "Basic information about a third party account link, including its type and type-specific information.")
@javax.annotation.Generated(value = "com.us.idl.javaidl.JavaIDLCodegen", date = "2021-08-24T20:55:04.712703200+02:00[Europe/Paris]")
public class ThirdPartyLinkSnippet {
  public static final String SERIALIZED_NAME_CHANNEL_TO_STORE_LINK = "channelToStoreLink";
  @SerializedName(SERIALIZED_NAME_CHANNEL_TO_STORE_LINK)
  private ChannelToStoreLinkDetails channelToStoreLink;

  /**
   * Type of the link named after the entities that are being linked.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    LINKUNSPECIFIED("linkUnspecified"),
    
    CHANNELTOSTORELINK("channelToStoreLink");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;


  public ThirdPartyLinkSnippet channelToStoreLink(ChannelToStoreLinkDetails channelToStoreLink) {
    
    this.channelToStoreLink = channelToStoreLink;
    return this;
  }

   /**
   * Get channelToStoreLink
   * @return channelToStoreLink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ChannelToStoreLinkDetails getChannelToStoreLink() {
    return channelToStoreLink;
  }


  public void setChannelToStoreLink(ChannelToStoreLinkDetails channelToStoreLink) {
    this.channelToStoreLink = channelToStoreLink;
  }


  public ThirdPartyLinkSnippet type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Type of the link named after the entities that are being linked.
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Type of the link named after the entities that are being linked.")

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThirdPartyLinkSnippet thirdPartyLinkSnippet = (ThirdPartyLinkSnippet) o;
    return Objects.equals(this.channelToStoreLink, thirdPartyLinkSnippet.channelToStoreLink) &&
        Objects.equals(this.type, thirdPartyLinkSnippet.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelToStoreLink, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThirdPartyLinkSnippet {\n");
    sb.append("    channelToStoreLink: ").append(toIndentedString(channelToStoreLink)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

