/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.VideoAbuseReportSecondaryReason;

/**
 * Basic details about a video category, such as its localized title.
 */
@ApiModel(description = "Basic details about a video category, such as its localized title.")
@javax.annotation.Generated(value = "com.us.idl.javaidl.JavaIDLCodegen", date = "2021-08-24T20:55:04.712703200+02:00[Europe/Paris]")
public class VideoAbuseReportReasonSnippet {
  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_SECONDARY_REASONS = "secondaryReasons";
  @SerializedName(SERIALIZED_NAME_SECONDARY_REASONS)
  private List<VideoAbuseReportSecondaryReason> secondaryReasons = null;


  public VideoAbuseReportReasonSnippet label(String label) {
    
    this.label = label;
    return this;
  }

   /**
   * The localized label belonging to this abuse report reason.
   * @return label
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The localized label belonging to this abuse report reason.")

  public String getLabel() {
    return label;
  }


  public void setLabel(String label) {
    this.label = label;
  }


  public VideoAbuseReportReasonSnippet secondaryReasons(List<VideoAbuseReportSecondaryReason> secondaryReasons) {
    
    this.secondaryReasons = secondaryReasons;
    return this;
  }

  public VideoAbuseReportReasonSnippet addSecondaryReasonsItem(VideoAbuseReportSecondaryReason secondaryReasonsItem) {
    if (this.secondaryReasons == null) {
      this.secondaryReasons = new ArrayList<VideoAbuseReportSecondaryReason>();
    }
    this.secondaryReasons.add(secondaryReasonsItem);
    return this;
  }

   /**
   * The secondary reasons associated with this reason, if any are available. (There might be 0 or more.)
   * @return secondaryReasons
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The secondary reasons associated with this reason, if any are available. (There might be 0 or more.)")

  public List<VideoAbuseReportSecondaryReason> getSecondaryReasons() {
    return secondaryReasons;
  }


  public void setSecondaryReasons(List<VideoAbuseReportSecondaryReason> secondaryReasons) {
    this.secondaryReasons = secondaryReasons;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VideoAbuseReportReasonSnippet videoAbuseReportReasonSnippet = (VideoAbuseReportReasonSnippet) o;
    return Objects.equals(this.label, videoAbuseReportReasonSnippet.label) &&
        Objects.equals(this.secondaryReasons, videoAbuseReportReasonSnippet.secondaryReasons);
  }

  @Override
  public int hashCode() {
    return Objects.hash(label, secondaryReasons);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VideoAbuseReportReasonSnippet {\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    secondaryReasons: ").append(toIndentedString(secondaryReasons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

