/*
 * YouTube Data API v3
 * The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.VideoAgeGating;
import org.openapitools.client.model.VideoContentDetails;
import org.openapitools.client.model.VideoFileDetails;
import org.openapitools.client.model.VideoLiveStreamingDetails;
import org.openapitools.client.model.VideoLocalization;
import org.openapitools.client.model.VideoMonetizationDetails;
import org.openapitools.client.model.VideoPlayer;
import org.openapitools.client.model.VideoProcessingDetails;
import org.openapitools.client.model.VideoRecordingDetails;
import org.openapitools.client.model.VideoSnippet;
import org.openapitools.client.model.VideoStatistics;
import org.openapitools.client.model.VideoStatus;
import org.openapitools.client.model.VideoSuggestions;
import org.openapitools.client.model.VideoTopicDetails;

/**
 * A *video* resource represents a YouTube video.
 */
@ApiModel(description = "A *video* resource represents a YouTube video.")
@javax.annotation.Generated(value = "com.us.idl.javaidl.JavaIDLCodegen", date = "2021-08-24T20:55:04.712703200+02:00[Europe/Paris]")
public class Video {
  public static final String SERIALIZED_NAME_AGE_GATING = "ageGating";
  @SerializedName(SERIALIZED_NAME_AGE_GATING)
  private VideoAgeGating ageGating;

  public static final String SERIALIZED_NAME_CONTENT_DETAILS = "contentDetails";
  @SerializedName(SERIALIZED_NAME_CONTENT_DETAILS)
  private VideoContentDetails contentDetails;

  public static final String SERIALIZED_NAME_ETAG = "etag";
  @SerializedName(SERIALIZED_NAME_ETAG)
  private String etag;

  public static final String SERIALIZED_NAME_FILE_DETAILS = "fileDetails";
  @SerializedName(SERIALIZED_NAME_FILE_DETAILS)
  private VideoFileDetails fileDetails;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  private String kind = "youtube#video";

  public static final String SERIALIZED_NAME_LIVE_STREAMING_DETAILS = "liveStreamingDetails";
  @SerializedName(SERIALIZED_NAME_LIVE_STREAMING_DETAILS)
  private VideoLiveStreamingDetails liveStreamingDetails;

  public static final String SERIALIZED_NAME_LOCALIZATIONS = "localizations";
  @SerializedName(SERIALIZED_NAME_LOCALIZATIONS)
  private Map<String, VideoLocalization> localizations = null;

  public static final String SERIALIZED_NAME_MONETIZATION_DETAILS = "monetizationDetails";
  @SerializedName(SERIALIZED_NAME_MONETIZATION_DETAILS)
  private VideoMonetizationDetails monetizationDetails;

  public static final String SERIALIZED_NAME_PLAYER = "player";
  @SerializedName(SERIALIZED_NAME_PLAYER)
  private VideoPlayer player;

  public static final String SERIALIZED_NAME_PROCESSING_DETAILS = "processingDetails";
  @SerializedName(SERIALIZED_NAME_PROCESSING_DETAILS)
  private VideoProcessingDetails processingDetails;

  public static final String SERIALIZED_NAME_PROJECT_DETAILS = "projectDetails";
  @SerializedName(SERIALIZED_NAME_PROJECT_DETAILS)
  private Object projectDetails;

  public static final String SERIALIZED_NAME_RECORDING_DETAILS = "recordingDetails";
  @SerializedName(SERIALIZED_NAME_RECORDING_DETAILS)
  private VideoRecordingDetails recordingDetails;

  public static final String SERIALIZED_NAME_SNIPPET = "snippet";
  @SerializedName(SERIALIZED_NAME_SNIPPET)
  private VideoSnippet snippet;

  public static final String SERIALIZED_NAME_STATISTICS = "statistics";
  @SerializedName(SERIALIZED_NAME_STATISTICS)
  private VideoStatistics statistics;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private VideoStatus status;

  public static final String SERIALIZED_NAME_SUGGESTIONS = "suggestions";
  @SerializedName(SERIALIZED_NAME_SUGGESTIONS)
  private VideoSuggestions suggestions;

  public static final String SERIALIZED_NAME_TOPIC_DETAILS = "topicDetails";
  @SerializedName(SERIALIZED_NAME_TOPIC_DETAILS)
  private VideoTopicDetails topicDetails;


  public Video ageGating(VideoAgeGating ageGating) {
    
    this.ageGating = ageGating;
    return this;
  }

   /**
   * Get ageGating
   * @return ageGating
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VideoAgeGating getAgeGating() {
    return ageGating;
  }


  public void setAgeGating(VideoAgeGating ageGating) {
    this.ageGating = ageGating;
  }


  public Video contentDetails(VideoContentDetails contentDetails) {
    
    this.contentDetails = contentDetails;
    return this;
  }

   /**
   * Get contentDetails
   * @return contentDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VideoContentDetails getContentDetails() {
    return contentDetails;
  }


  public void setContentDetails(VideoContentDetails contentDetails) {
    this.contentDetails = contentDetails;
  }


  public Video etag(String etag) {
    
    this.etag = etag;
    return this;
  }

   /**
   * Etag of this resource.
   * @return etag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Etag of this resource.")

  public String getEtag() {
    return etag;
  }


  public void setEtag(String etag) {
    this.etag = etag;
  }


  public Video fileDetails(VideoFileDetails fileDetails) {
    
    this.fileDetails = fileDetails;
    return this;
  }

   /**
   * Get fileDetails
   * @return fileDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VideoFileDetails getFileDetails() {
    return fileDetails;
  }


  public void setFileDetails(VideoFileDetails fileDetails) {
    this.fileDetails = fileDetails;
  }


  public Video id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The ID that YouTube uses to uniquely identify the video.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID that YouTube uses to uniquely identify the video.")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Video kind(String kind) {
    
    this.kind = kind;
    return this;
  }

   /**
   * Identifies what kind of resource this is. Value: the fixed string \&quot;youtube#video\&quot;.
   * @return kind
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Identifies what kind of resource this is. Value: the fixed string \"youtube#video\".")

  public String getKind() {
    return kind;
  }


  public void setKind(String kind) {
    this.kind = kind;
  }


  public Video liveStreamingDetails(VideoLiveStreamingDetails liveStreamingDetails) {
    
    this.liveStreamingDetails = liveStreamingDetails;
    return this;
  }

   /**
   * Get liveStreamingDetails
   * @return liveStreamingDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VideoLiveStreamingDetails getLiveStreamingDetails() {
    return liveStreamingDetails;
  }


  public void setLiveStreamingDetails(VideoLiveStreamingDetails liveStreamingDetails) {
    this.liveStreamingDetails = liveStreamingDetails;
  }


  public Video localizations(Map<String, VideoLocalization> localizations) {
    
    this.localizations = localizations;
    return this;
  }

  public Video putLocalizationsItem(String key, VideoLocalization localizationsItem) {
    if (this.localizations == null) {
      this.localizations = new HashMap<String, VideoLocalization>();
    }
    this.localizations.put(key, localizationsItem);
    return this;
  }

   /**
   * The localizations object contains localized versions of the basic details about the video, such as its title and description.
   * @return localizations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The localizations object contains localized versions of the basic details about the video, such as its title and description.")

  public Map<String, VideoLocalization> getLocalizations() {
    return localizations;
  }


  public void setLocalizations(Map<String, VideoLocalization> localizations) {
    this.localizations = localizations;
  }


  public Video monetizationDetails(VideoMonetizationDetails monetizationDetails) {
    
    this.monetizationDetails = monetizationDetails;
    return this;
  }

   /**
   * Get monetizationDetails
   * @return monetizationDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VideoMonetizationDetails getMonetizationDetails() {
    return monetizationDetails;
  }


  public void setMonetizationDetails(VideoMonetizationDetails monetizationDetails) {
    this.monetizationDetails = monetizationDetails;
  }


  public Video player(VideoPlayer player) {
    
    this.player = player;
    return this;
  }

   /**
   * Get player
   * @return player
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VideoPlayer getPlayer() {
    return player;
  }


  public void setPlayer(VideoPlayer player) {
    this.player = player;
  }


  public Video processingDetails(VideoProcessingDetails processingDetails) {
    
    this.processingDetails = processingDetails;
    return this;
  }

   /**
   * Get processingDetails
   * @return processingDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VideoProcessingDetails getProcessingDetails() {
    return processingDetails;
  }


  public void setProcessingDetails(VideoProcessingDetails processingDetails) {
    this.processingDetails = processingDetails;
  }


  public Video projectDetails(Object projectDetails) {
    
    this.projectDetails = projectDetails;
    return this;
  }

   /**
   * DEPRECATED. b/157517979: This part was never populated after it was added. However, it sees non-zero traffic because there is generated client code in the wild that refers to it [1]. We keep this field and do NOT remove it because otherwise V3 would return an error when this part gets requested [2]. [1] https://developers.google.com/resources/api-libraries/documentation/youtube/v3/csharp/latest/classGoogle_1_1Apis_1_1YouTube_1_1v3_1_1Data_1_1VideoProjectDetails.html [2] http://google3/video/youtube/src/python/servers/data_api/common.py?l&#x3D;1565-1569&amp;rcl&#x3D;344141677
   * @return projectDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "DEPRECATED. b/157517979: This part was never populated after it was added. However, it sees non-zero traffic because there is generated client code in the wild that refers to it [1]. We keep this field and do NOT remove it because otherwise V3 would return an error when this part gets requested [2]. [1] https://developers.google.com/resources/api-libraries/documentation/youtube/v3/csharp/latest/classGoogle_1_1Apis_1_1YouTube_1_1v3_1_1Data_1_1VideoProjectDetails.html [2] http://google3/video/youtube/src/python/servers/data_api/common.py?l=1565-1569&rcl=344141677")

  public Object getProjectDetails() {
    return projectDetails;
  }


  public void setProjectDetails(Object projectDetails) {
    this.projectDetails = projectDetails;
  }


  public Video recordingDetails(VideoRecordingDetails recordingDetails) {
    
    this.recordingDetails = recordingDetails;
    return this;
  }

   /**
   * Get recordingDetails
   * @return recordingDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VideoRecordingDetails getRecordingDetails() {
    return recordingDetails;
  }


  public void setRecordingDetails(VideoRecordingDetails recordingDetails) {
    this.recordingDetails = recordingDetails;
  }


  public Video snippet(VideoSnippet snippet) {
    
    this.snippet = snippet;
    return this;
  }

   /**
   * Get snippet
   * @return snippet
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VideoSnippet getSnippet() {
    return snippet;
  }


  public void setSnippet(VideoSnippet snippet) {
    this.snippet = snippet;
  }


  public Video statistics(VideoStatistics statistics) {
    
    this.statistics = statistics;
    return this;
  }

   /**
   * Get statistics
   * @return statistics
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VideoStatistics getStatistics() {
    return statistics;
  }


  public void setStatistics(VideoStatistics statistics) {
    this.statistics = statistics;
  }


  public Video status(VideoStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VideoStatus getStatus() {
    return status;
  }


  public void setStatus(VideoStatus status) {
    this.status = status;
  }


  public Video suggestions(VideoSuggestions suggestions) {
    
    this.suggestions = suggestions;
    return this;
  }

   /**
   * Get suggestions
   * @return suggestions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VideoSuggestions getSuggestions() {
    return suggestions;
  }


  public void setSuggestions(VideoSuggestions suggestions) {
    this.suggestions = suggestions;
  }


  public Video topicDetails(VideoTopicDetails topicDetails) {
    
    this.topicDetails = topicDetails;
    return this;
  }

   /**
   * Get topicDetails
   * @return topicDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VideoTopicDetails getTopicDetails() {
    return topicDetails;
  }


  public void setTopicDetails(VideoTopicDetails topicDetails) {
    this.topicDetails = topicDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Video video = (Video) o;
    return Objects.equals(this.ageGating, video.ageGating) &&
        Objects.equals(this.contentDetails, video.contentDetails) &&
        Objects.equals(this.etag, video.etag) &&
        Objects.equals(this.fileDetails, video.fileDetails) &&
        Objects.equals(this.id, video.id) &&
        Objects.equals(this.kind, video.kind) &&
        Objects.equals(this.liveStreamingDetails, video.liveStreamingDetails) &&
        Objects.equals(this.localizations, video.localizations) &&
        Objects.equals(this.monetizationDetails, video.monetizationDetails) &&
        Objects.equals(this.player, video.player) &&
        Objects.equals(this.processingDetails, video.processingDetails) &&
        Objects.equals(this.projectDetails, video.projectDetails) &&
        Objects.equals(this.recordingDetails, video.recordingDetails) &&
        Objects.equals(this.snippet, video.snippet) &&
        Objects.equals(this.statistics, video.statistics) &&
        Objects.equals(this.status, video.status) &&
        Objects.equals(this.suggestions, video.suggestions) &&
        Objects.equals(this.topicDetails, video.topicDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ageGating, contentDetails, etag, fileDetails, id, kind, liveStreamingDetails, localizations, monetizationDetails, player, processingDetails, projectDetails, recordingDetails, snippet, statistics, status, suggestions, topicDetails);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Video {\n");
    sb.append("    ageGating: ").append(toIndentedString(ageGating)).append("\n");
    sb.append("    contentDetails: ").append(toIndentedString(contentDetails)).append("\n");
    sb.append("    etag: ").append(toIndentedString(etag)).append("\n");
    sb.append("    fileDetails: ").append(toIndentedString(fileDetails)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    liveStreamingDetails: ").append(toIndentedString(liveStreamingDetails)).append("\n");
    sb.append("    localizations: ").append(toIndentedString(localizations)).append("\n");
    sb.append("    monetizationDetails: ").append(toIndentedString(monetizationDetails)).append("\n");
    sb.append("    player: ").append(toIndentedString(player)).append("\n");
    sb.append("    processingDetails: ").append(toIndentedString(processingDetails)).append("\n");
    sb.append("    projectDetails: ").append(toIndentedString(projectDetails)).append("\n");
    sb.append("    recordingDetails: ").append(toIndentedString(recordingDetails)).append("\n");
    sb.append("    snippet: ").append(toIndentedString(snippet)).append("\n");
    sb.append("    statistics: ").append(toIndentedString(statistics)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    suggestions: ").append(toIndentedString(suggestions)).append("\n");
    sb.append("    topicDetails: ").append(toIndentedString(topicDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

